In [1]:
# Load standard libraries
import os
import json
import sys
import pandas as pd
import requests
from dotenv import load_dotenv
import time

import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import matplotlib.ticker as mtick
from matplotlib.dates import MonthLocator, AutoDateLocator, ConciseDateFormatter, MO
from matplotlib.ticker import FuncFormatter, PercentFormatter, StrMethodFormatter

import datetime

from IPython.display import HTML

# Load env variables
load_dotenv("API_KEYS.env")
blockworks_api_key = os.getenv("BLOCKWORKS_API_KEY")
coingecko_api_key = os.getenv("COINGECKO_API_KEY")
dune_api_key = os.getenv("DUNE_API_KEY")
messari_api_key = os.getenv("MESSARI_API_KEY")
fred_api_key = os.getenv("FRED_API_KEY")

# Import data collection and processing functions
sys.path.append('src')
from data import blockworks
from data import coingecko
from data import metadao
from data import hyperliquid
from data import defillama
from data import dune
from data import messari
from data import yahoofinance
from data import fred
from data import data_processing
from data import protocol_index as pi

# Import utils functions
sys.path.append('utils')
import helper_functions
today = datetime.datetime.today()
date = helper_functions.format_date_with_suffix(today)

# Load output directories
blockworks_output_dir = 'data/raw/blockworks'
coingecko_output_dir = 'data/raw/coingecko'
defillama_output_dir = 'data/raw/defillama'
dune_output_dir = 'data/raw/dune'
fred_output_dir = 'data/raw/fred'
messari_output_dir = 'data/raw/messari'
metadao_output_dir = 'data/raw/metadao'
metadao_processed_dir = 'data/processed/metadao'
hyperliquid_output_dir = 'data/raw/hyperliquid'
yahoofinance_output_dir = 'data/raw/yahoofinance'

**Optional: clear existing raw data.** The pull functions now skip any file whose newest data point is within 3 days, and fetch the rest in parallel. Skip the next cell to repull only stale or missing files (fast). Run it to force a full repull. You can also pass `max_stale_days=None` to any DefiLlama or Messari pull to force a repull without deleting. With `DEFILLAMA_API_KEY` in `API_KEYS.env` the DefiLlama pulls run on the Pro host (`pro-api.llama.fi`, 1,000 req/min) at 16 requests in flight instead of 6 on the free host; the payloads are identical.

In [2]:
# Clear all existing raw data, you will be prompted for yes/no
directory_path = 'data/'
helper_functions.delete_directories(directory_path)

Found 899 files to delete

KeyboardInterrupt: Interrupted by user

**Blockworks.** The Research API key has a monthly usage cap. When it is reached every request answers `429 Monthly usage limit reached` and the pull below stops after its first request, prints the reset estimate and reports the skipped pairs, so the cell takes seconds rather than retrying ~100 requests. Files whose newest point is within 3 days are not repulled (pass `max_stale_days=None` to force), and each metric is fetched in one comma-separated request for all stale projects. Blockworks' current Data API (`/query/timeseries/...`, header `X-Blockworks-API-Key`) carries the same chain and lending metrics but needs a paid key with the `blockchains_unified` and `projects_protocols_unified` permissions; the Research API key is not accepted there.

In [ ]:
# BLOCKWORKS
start_date = '2020-01-01'
end_date = datetime.datetime.today().strftime('%Y-%m-%d')

In [ ]:
# Pull Blockworks data using protocol index
# Categories are pulled from config/protocol_index.json

blockworks_categories = ['smart_contract_chains',
                         'borrow_lend_protocols']

# Build categories dict with Blockworks slugs from the centralized index
categories = pi.get_categories_dict(categories=blockworks_categories, source='blockworks')

metrics = ['rev-usd',
           'transaction-fee-avg-usd',
           'transaction-total',
           'interest-total-usd',
           'nii-total-usd',
           'revenue-total-usd',
           'borrow-total-usd',
           'deposit-total-usd'
          ]

# Call the function
for category, assets in categories.items():
    print(f'{category}:')
    print()
    blockworks.pull_asset_data(assets.keys(), metrics, start_date, end_date, blockworks_api_key, blockworks_output_dir)
    print()
    print('---------------------------')
print('Done')

smart_contract_chains:

Blockworks rev-usd:   0%|          | 0/1 [00:00<?, ?pull/s]

Blockworks rev-usd: 100%|██████████| 1/1 [00:04<00:00,  4.60s/pull]
Blockworks transaction-fee-avg-usd: 100%|██████████| 1/1 [00:02<00:00,  2.73s/pull]
Blockworks transaction-total: 100%|██████████| 1/1 [00:00<00:00,  1.02pull/s]
Blockworks interest-total-usd:   0%|          | 0/1 [00:00<?, ?pull/s]

  Error fetching interest-total-usd for ethereum: 404 Client Error: Not Found for url: https://api.blockworks.com/v1/metrics/interest-total-usd?project=ethereum&start_date=2020-01-01&end_date=2026-10-10
  Error fetching interest-total-usd for solana: 404 Client Error: Not Found for url: https://api.blockworks.com/v1/metrics/interest-total-usd?project=solana&start_date=2020-01-01&end_date=2026-10-10
  Error fetching interest-total-usd for bnb: 404 Client Error: Not Found for url: https://api.blockworks.com/v1/metrics/interest-total-usd?project=bnb&start_date=2020-01-01&end_date=2026-10-10
  Error fetching interest-total-usd for arbitrum: 404 Client Error: Not Found for url: https://api.blockworks.com/v1/metrics/interest-total-usd?project=arbitrum&start_date=2020-01-01&end_date=2026-10-10
  Error fetching interest-total-usd for tron: 404 Client Error: Not Found for url: https://api.blockworks.com/v1/metrics/interest-total-usd?project=tron&start_date=2020-01-01&end_date=2026-10-10
  Error fetching interest-total-usd for base: 404 Client Error: Not Found for url: https://api.blockworks.com/v1/metrics/interest-total-usd?project=base&start_date=2020-01-01&end_date=2026-10-10

Blockworks interest-total-usd: 100%|██████████| 1/1 [00:00<00:00,  1.21pull/s]
Blockworks nii-total-usd:   0%|          | 0/1 [00:00<?, ?pull/s]

  Error fetching nii-total-usd for ethereum: 404 Client Error: Not Found for url: https://api.blockworks.com/v1/metrics/nii-total-usd?project=ethereum&start_date=2020-01-01&end_date=2026-10-10
  Error fetching nii-total-usd for solana: 404 Client Error: Not Found for url: https://api.blockworks.com/v1/metrics/nii-total-usd?project=solana&start_date=2020-01-01&end_date=2026-10-10
  Error fetching nii-total-usd for bnb: 404 Client Error: Not Found for url: https://api.blockworks.com/v1/metrics/nii-total-usd?project=bnb&start_date=2020-01-01&end_date=2026-10-10
  Error fetching nii-total-usd for arbitrum: 404 Client Error: Not Found for url: https://api.blockworks.com/v1/metrics/nii-total-usd?project=arbitrum&start_date=2020-01-01&end_date=2026-10-10
  Error fetching nii-total-usd for tron: 404 Client Error: Not Found for url: https://api.blockworks.com/v1/metrics/nii-total-usd?project=tron&start_date=2020-01-01&end_date=2026-10-10

Blockworks nii-total-usd: 100%|██████████| 1/1 [00:01<00:00,  1.30s/pull]

  Error fetching nii-total-usd for base: 404 Client Error: Not Found for url: https://api.blockworks.com/v1/metrics/nii-total-usd?project=base&start_date=2020-01-01&end_date=2026-10-10

Blockworks revenue-total-usd:   0%|          | 0/1 [00:00<?, ?pull/s]

  Error fetching revenue-total-usd for ethereum: 404 Client Error: Not Found for url: https://api.blockworks.com/v1/metrics/revenue-total-usd?project=ethereum&start_date=2020-01-01&end_date=2026-10-10
  Error fetching revenue-total-usd for solana: 404 Client Error: Not Found for url: https://api.blockworks.com/v1/metrics/revenue-total-usd?project=solana&start_date=2020-01-01&end_date=2026-10-10
  Error fetching revenue-total-usd for bnb: 404 Client Error: Not Found for url: https://api.blockworks.com/v1/metrics/revenue-total-usd?project=bnb&start_date=2020-01-01&end_date=2026-10-10
  Error fetching revenue-total-usd for arbitrum: 404 Client Error: Not Found for url: https://api.blockworks.com/v1/metrics/revenue-total-usd?project=arbitrum&start_date=2020-01-01&end_date=2026-10-10
  Error fetching revenue-total-usd for tron: 404 Client Error: Not Found for url: https://api.blockworks.com/v1/metrics/revenue-total-usd?project=tron&start_date=2020-01-01&end_date=2026-10-10

Blockworks revenue-total-usd: 100%|██████████| 1/1 [00:00<00:00,  1.28pull/s]

  Error fetching revenue-total-usd for base: 404 Client Error: Not Found for url: https://api.blockworks.com/v1/metrics/revenue-total-usd?project=base&start_date=2020-01-01&end_date=2026-10-10

Blockworks borrow-total-usd:   0%|          | 0/1 [00:00<?, ?pull/s]

  Error fetching borrow-total-usd for ethereum: 404 Client Error: Not Found for url: https://api.blockworks.com/v1/metrics/borrow-total-usd?project=ethereum&start_date=2020-01-01&end_date=2026-10-10
  Error fetching borrow-total-usd for solana: 404 Client Error: Not Found for url: https://api.blockworks.com/v1/metrics/borrow-total-usd?project=solana&start_date=2020-01-01&end_date=2026-10-10
  Error fetching borrow-total-usd for bnb: 404 Client Error: Not Found for url: https://api.blockworks.com/v1/metrics/borrow-total-usd?project=bnb&start_date=2020-01-01&end_date=2026-10-10
  Error fetching borrow-total-usd for arbitrum: 404 Client Error: Not Found for url: https://api.blockworks.com/v1/metrics/borrow-total-usd?project=arbitrum&start_date=2020-01-01&end_date=2026-10-10
  Error fetching borrow-total-usd for tron: 404 Client Error: Not Found for url: https://api.blockworks.com/v1/metrics/borrow-total-usd?project=tron&start_date=2020-01-01&end_date=2026-10-10

Blockworks borrow-total-usd: 100%|██████████| 1/1 [00:00<00:00,  1.35pull/s]

  Error fetching borrow-total-usd for base: 404 Client Error: Not Found for url: https://api.blockworks.com/v1/metrics/borrow-total-usd?project=base&start_date=2020-01-01&end_date=2026-10-10

Blockworks deposit-total-usd:   0%|          | 0/1 [00:00<?, ?pull/s]

  Error fetching deposit-total-usd for ethereum: 404 Client Error: Not Found for url: https://api.blockworks.com/v1/metrics/deposit-total-usd?project=ethereum&start_date=2020-01-01&end_date=2026-10-10
  Error fetching deposit-total-usd for solana: 404 Client Error: Not Found for url: https://api.blockworks.com/v1/metrics/deposit-total-usd?project=solana&start_date=2020-01-01&end_date=2026-10-10
  Error fetching deposit-total-usd for bnb: 404 Client Error: Not Found for url: https://api.blockworks.com/v1/metrics/deposit-total-usd?project=bnb&start_date=2020-01-01&end_date=2026-10-10

Blockworks deposit-total-usd: 100%|██████████| 1/1 [00:00<00:00,  1.35pull/s]

  Error fetching deposit-total-usd for arbitrum: 404 Client Error: Not Found for url: https://api.blockworks.com/v1/metrics/deposit-total-usd?project=arbitrum&start_date=2020-01-01&end_date=2026-10-10
  Error fetching deposit-total-usd for tron: 404 Client Error: Not Found for url: https://api.blockworks.com/v1/metrics/deposit-total-usd?project=tron&start_date=2020-01-01&end_date=2026-10-10
  Error fetching deposit-total-usd for base: 404 Client Error: Not Found for url: https://api.blockworks.com/v1/metrics/deposit-total-usd?project=base&start_date=2020-01-01&end_date=2026-10-10

Blockworks deposit-total-usd: 100%|██████████| 1/1 [00:00<00:00,  1.35pull/s]

All rev-usd data saved to data/raw/blockworks/rev-usd/
All transaction-fee-avg-usd data saved to data/raw/blockworks/transaction-fee-avg-usd/
All transaction-total data saved to data/raw/blockworks/transaction-total/
All interest-total-usd data saved to data/raw/blockworks/interest-total-usd/
All nii-total-usd data saved to data/raw/blockworks/nii-total-usd/
All revenue-total-usd data saved to data/raw/blockworks/revenue-total-usd/
All borrow-total-usd data saved to data/raw/blockworks/borrow-total-usd/
All deposit-total-usd data saved to data/raw/blockworks/deposit-total-usd/

Failed to pull (30):
  borrow-total-usd:
    - arbitrum
    - base
    - bnb
    - ethereum
    - solana
    - tron
  deposit-total-usd:
    - arbitrum
    - base
    - bnb
    - ethereum
    - solana
    - tron
  interest-total-usd:
    - arbitrum
    - base
    - bnb
    - ethereum
    - solana
    - tron
  nii-total-usd:
    - arbitrum
    - base
    - bnb
    - ethereum
    - solana
    - tron
  revenue-total-usd:
    - arbitrum
    - base
    - bnb
    - ethereum
    - solana
    - tron

---------------------------
borrow_lend_protocols:

Blockworks rev-usd:   0%|          | 0/1 [00:00<?, ?pull/s]

  Error fetching rev-usd for aave: 404 Client Error: Not Found for url: https://api.blockworks.com/v1/metrics/rev-usd?project=aave&start_date=2020-01-01&end_date=2026-10-10
  Error fetching rev-usd for morpho: 404 Client Error: Not Found for url: https://api.blockworks.com/v1/metrics/rev-usd?project=morpho&start_date=2020-01-01&end_date=2026-10-10
  Error fetching rev-usd for kamino: 404 Client Error: Not Found for url: https://api.blockworks.com/v1/metrics/rev-usd?project=kamino&start_date=2020-01-01&end_date=2026-10-10

Blockworks rev-usd: 100%|██████████| 1/1 [00:00<00:00,  1.60pull/s]

  Error fetching rev-usd for euler: 404 Client Error: Not Found for url: https://api.blockworks.com/v1/metrics/rev-usd?project=euler&start_date=2020-01-01&end_date=2026-10-10
  Error fetching rev-usd for spark: 404 Client Error: Not Found for url: https://api.blockworks.com/v1/metrics/rev-usd?project=spark&start_date=2020-01-01&end_date=2026-10-10

Blockworks transaction-fee-avg-usd:   0%|          | 0/1 [00:00<?, ?pull/s]

  Error fetching transaction-fee-avg-usd for aave: 404 Client Error: Not Found for url: https://api.blockworks.com/v1/metrics/transaction-fee-avg-usd?project=aave&start_date=2020-01-01&end_date=2026-10-10
  Error fetching transaction-fee-avg-usd for morpho: 404 Client Error: Not Found for url: https://api.blockworks.com/v1/metrics/transaction-fee-avg-usd?project=morpho&start_date=2020-01-01&end_date=2026-10-10
  Error fetching transaction-fee-avg-usd for kamino: 404 Client Error: Not Found for url: https://api.blockworks.com/v1/metrics/transaction-fee-avg-usd?project=kamino&start_date=2020-01-01&end_date=2026-10-10

Blockworks transaction-fee-avg-usd: 100%|██████████| 1/1 [00:00<00:00,  1.57pull/s]

  Error fetching transaction-fee-avg-usd for euler: 404 Client Error: Not Found for url: https://api.blockworks.com/v1/metrics/transaction-fee-avg-usd?project=euler&start_date=2020-01-01&end_date=2026-10-10
  Error fetching transaction-fee-avg-usd for spark: 404 Client Error: Not Found for url: https://api.blockworks.com/v1/metrics/transaction-fee-avg-usd?project=spark&start_date=2020-01-01&end_date=2026-10-10

Blockworks transaction-total:   0%|          | 0/1 [00:00<?, ?pull/s]

  Error fetching transaction-total for aave: 404 Client Error: Not Found for url: https://api.blockworks.com/v1/metrics/transaction-total?project=aave&start_date=2020-01-01&end_date=2026-10-10
  Error fetching transaction-total for morpho: 404 Client Error: Not Found for url: https://api.blockworks.com/v1/metrics/transaction-total?project=morpho&start_date=2020-01-01&end_date=2026-10-10
  Error fetching transaction-total for kamino: 404 Client Error: Not Found for url: https://api.blockworks.com/v1/metrics/transaction-total?project=kamino&start_date=2020-01-01&end_date=2026-10-10

Blockworks transaction-total: 100%|██████████| 1/1 [00:00<00:00,  1.54pull/s]

  Error fetching transaction-total for euler: 404 Client Error: Not Found for url: https://api.blockworks.com/v1/metrics/transaction-total?project=euler&start_date=2020-01-01&end_date=2026-10-10
  Error fetching transaction-total for spark: 404 Client Error: Not Found for url: https://api.blockworks.com/v1/metrics/transaction-total?project=spark&start_date=2020-01-01&end_date=2026-10-10

Blockworks interest-total-usd:   0%|          | 0/1 [00:00<?, ?pull/s]

  Error fetching interest-total-usd for euler: 404 Client Error: Not Found for url: https://api.blockworks.com/v1/metrics/interest-total-usd?project=euler&start_date=2020-01-01&end_date=2026-10-10

Blockworks interest-total-usd: 100%|██████████| 1/1 [00:08<00:00,  8.76s/pull]
Blockworks nii-total-usd:   0%|          | 0/1 [00:00<?, ?pull/s]

  Error fetching nii-total-usd for euler: 404 Client Error: Not Found for url: https://api.blockworks.com/v1/metrics/nii-total-usd?project=euler&start_date=2020-01-01&end_date=2026-10-10

Blockworks nii-total-usd: 100%|██████████| 1/1 [00:07<00:00,  7.24s/pull]
Blockworks revenue-total-usd: 100%|██████████| 1/1 [00:01<00:00,  1.04s/pull]
Blockworks borrow-total-usd:   0%|          | 0/1 [00:00<?, ?pull/s]

  Error fetching borrow-total-usd for euler: 404 Client Error: Not Found for url: https://api.blockworks.com/v1/metrics/borrow-total-usd?project=euler&start_date=2020-01-01&end_date=2026-10-10

Blockworks borrow-total-usd: 100%|██████████| 1/1 [00:07<00:00,  7.95s/pull]
Blockworks deposit-total-usd:   0%|          | 0/1 [00:00<?, ?pull/s]

  Error fetching deposit-total-usd for euler: 404 Client Error: Not Found for url: https://api.blockworks.com/v1/metrics/deposit-total-usd?project=euler&start_date=2020-01-01&end_date=2026-10-10

Blockworks deposit-total-usd: 100%|██████████| 1/1 [00:08<00:00,  8.16s/pull]

All rev-usd data saved to data/raw/blockworks/rev-usd/
All transaction-fee-avg-usd data saved to data/raw/blockworks/transaction-fee-avg-usd/
All transaction-total data saved to data/raw/blockworks/transaction-total/
All interest-total-usd data saved to data/raw/blockworks/interest-total-usd/
All nii-total-usd data saved to data/raw/blockworks/nii-total-usd/
All revenue-total-usd data saved to data/raw/blockworks/revenue-total-usd/
All borrow-total-usd data saved to data/raw/blockworks/borrow-total-usd/
All deposit-total-usd data saved to data/raw/blockworks/deposit-total-usd/

Failed to pull (19):
  borrow-total-usd:
    - euler
  deposit-total-usd:
    - euler
  interest-total-usd:
    - euler
  nii-total-usd:
    - euler
  rev-usd:
    - aave
    - euler
    - kamino
    - morpho
    - spark
  transaction-fee-avg-usd:
    - aave
    - euler
    - kamino
    - morpho
    - spark
  transaction-total:
    - aave
    - euler
    - kamino
    - morpho
    - spark

---------------------------
Done

In [ ]:
# Pull a single metric for ALL projects that track it.
# Project coverage is discovered from the Blockworks metrics catalog (GET /v1/metrics?identifier=...),
# e.g. https://docs.blockworksresearch.com/api-reference/metrics/hyperliquid/dex-spot-volume-total-usd

metrics_for_all_projects = ['rev-usd',                    # REV (real economic value)
                            'dex-spot-volume-total-usd']  # spot DEX volume

for metric in metrics_for_all_projects:
    print(f'{metric}:')
    print()
    blockworks.pull_metric_data(metric, start_date, end_date, blockworks_api_key, blockworks_output_dir)
    print()
    print('---------------------------')
print('Done')

rev-usd:

Found 39 projects tracking 'rev-usd'
Blockworks rev-usd: 6 fresh file(s) skipped, 33 to pull

Blockworks rev-usd: 100%|██████████| 2/2 [00:09<00:00,  4.98s/pull]

All rev-usd data saved to data/raw/blockworks/rev-usd/

---------------------------
dex-spot-volume-total-usd:

Found 23 projects tracking 'dex-spot-volume-total-usd'

Blockworks dex-spot-volume-total-usd:   0%|          | 0/2 [00:00<?, ?pull/s]

  Error fetching dex-spot-volume-total-usd for megaeth: 500 Server Error: Internal Server Error for url: https://api.blockworks.com/v1/metrics/dex-spot-volume-total-usd?project=megaeth&start_date=2020-01-01&end_date=2026-10-10

Blockworks dex-spot-volume-total-usd: 100%|██████████| 2/2 [00:37<00:00, 18.76s/pull]

All dex-spot-volume-total-usd data saved to data/raw/blockworks/dex-spot-volume-total-usd/

Failed to pull (1):
  dex-spot-volume-total-usd:
    - megaeth

---------------------------
Done

In [ ]:
# Calculate borrow/lend efficiency ratios for the Blockworks borrow/lend protocols
# Computes (per protocol, per date): interest generated / total borrows, net interest income / total borrows, revenue / total borrows, interest generated / total deposits, net interest income / total deposits, revenue / total deposits, and total borrows / total deposits, then saves as a processed data file.

# Pull the Blockworks slugs for the borrow/lend protocols from the centralized index
borrow_lend_protocols = pi.get_blockworks_assets_dict(category='borrow_lend_protocols')

data_processing.calculate_borrow_lend_ratios(
    protocols=borrow_lend_protocols,
    blockworks_output_dir=blockworks_output_dir,
    output_filepath='data/processed/borrow-lend/borrow-lend-ratios.json'
)

Processing aave...
  Computed ratios for 2139 dates
Processing morpho...
  Computed ratios for 1010 dates
Processing kamino...
  Computed ratios for 1093 dates
Processing euler...
  Warning: missing metric(s) for euler: interest-total-usd, nii-total-usd, borrow-total-usd, deposit-total-usd
  Computed ratios for 778 dates
Processing spark...
  Computed ratios for 1291 dates

Borrow/lend ratios saved to: data/processed/borrow-lend/borrow-lend-ratios.json
Protocols processed: 5
Done

In [ ]:
# DEFILLAMA
window = 'total30d' # How long a time period to look back when aggregating protocols to categories. Can be 'total24h', 'total7d', 'total30d', 'total1y', or 'totalAllTime'; defaults to 'totalAllTime'

In [ ]:
# Test pull all protocols by metric function
metrics = {'dailyFees': 'fees',
          'dailyRevenue': 'revenue',
          'dailyHoldersRevenue': 'holders-revenue',
          'tvl': 'tvl'
}
defillama.pull_all_protocols_metric(metrics, defillama_output_dir)

DefiLlama all-protocol metrics: 100%|██████████| 4/4 [00:11<00:00,  2.94s/pull]

All fees data saved to data/raw/defillama/fees/
All revenue data saved to data/raw/defillama/revenue/
All holders-revenue data saved to data/raw/defillama/holders-revenue/
All tvl data saved to data/raw/defillama/tvl/

In [ ]:
# Test pulling fees and revenue data function
metrics = {'dailyFees': 'fees',
          'dailyRevenue': 'revenue',
          'dailyHoldersRevenue': 'holders-revenue',
          'dailyIncentives': 'incentives',   # Pro only (DEFILLAMA_API_KEY); daily token incentives, USD
          'tvl': 'tvl'
}


categories = {
    'perps_dexs':{'hyperliquid': 'hyperliquid'
             },
    'smart_contract_chains': {'ethereum': 'ethereum'
             },
    'borrow_lend_protocols' : {'kamino': 'kamino'
            },
    'derivatives': {'derive': 'derive'},
    'misc': {'M0': 'M0',
             'axiom': 'axiom',
             'angstrom': 'angstrom'}
}

for category, assets in categories.items():
    print(f'{category}:') 
    print()
    defillama.pull_metric_data_by_asset(metrics, assets, defillama_output_dir)
    print()
    print('---------------------------')
print('Done')

perps_dexs:

DefiLlama metric data: 100%|██████████| 5/5 [00:02<00:00,  2.01pull/s]

All fees data saved to data/raw/defillama/fees/
All revenue data saved to data/raw/defillama/revenue/
All holders-revenue data saved to data/raw/defillama/holders-revenue/
All incentives data saved to data/raw/defillama/incentives/
All tvl data saved to data/raw/defillama/tvl/

---------------------------
smart_contract_chains:

DefiLlama metric data: 100%|██████████| 5/5 [00:11<00:00,  2.32s/pull]

All fees data saved to data/raw/defillama/fees/
All revenue data saved to data/raw/defillama/revenue/
All holders-revenue data saved to data/raw/defillama/holders-revenue/
All incentives data saved to data/raw/defillama/incentives/
All tvl data saved to data/raw/defillama/tvl/

---------------------------
borrow_lend_protocols:

DefiLlama metric data: 100%|██████████| 5/5 [00:02<00:00,  1.77pull/s]

All fees data saved to data/raw/defillama/fees/
All revenue data saved to data/raw/defillama/revenue/
All holders-revenue data saved to data/raw/defillama/holders-revenue/
All incentives data saved to data/raw/defillama/incentives/
All tvl data saved to data/raw/defillama/tvl/

---------------------------
derivatives:

DefiLlama metric data: 100%|██████████| 5/5 [00:02<00:00,  1.79pull/s]

All fees data saved to data/raw/defillama/fees/
All revenue data saved to data/raw/defillama/revenue/
All holders-revenue data saved to data/raw/defillama/holders-revenue/
All incentives data saved to data/raw/defillama/incentives/
All tvl data saved to data/raw/defillama/tvl/

---------------------------
misc:

DefiLlama metric data:  67%|██████▋   | 10/15 [00:01<00:00, 10.95pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/angstrom?dataType=dailyHoldersRevenue

DefiLlama metric data: 100%|██████████| 15/15 [00:03<00:00,  4.35pull/s]

All fees data saved to data/raw/defillama/fees/
All revenue data saved to data/raw/defillama/revenue/
All holders-revenue data saved to data/raw/defillama/holders-revenue/
All incentives data saved to data/raw/defillama/incentives/
All tvl data saved to data/raw/defillama/tvl/

Failed to pull (1):
  holders-revenue:
    - angstrom

---------------------------
Done

In [ ]:
# Test function to establish categories by parent protocol
parent_categories = data_processing.establish_parent_protocols(
    defillama_output_dir=defillama_output_dir, window=window
)

Establishing parent protocol categories using fees data...
Step 1: Collecting all parent-child relationships and metrics from fees, revenue, and TVL data...
  Checking fees data...
  Checking revenue data...
  Checking holders-revenue data...
  Checking tvl data...
  Found 7255 unique parent protocols

Step 2: Analyzing fees data to determine parent categories...

Parent protocols saved to: data/processed/parent_protocols.json
Total parent protocols: 1642
Done

In [ ]:
# Test function to pull total fees by category
parent_protocols_path = 'data/processed/parent_protocols.json'
    
category_fees = data_processing.calculate_total_fees_by_category(
        parent_protocols_path=parent_protocols_path
    )

Loading parent protocols from data/processed/parent_protocols.json...

Found 81 categories

Top 10 categories by total fees:
  1. Super App: $849,567,119
  2. Stablecoin Issuer: $543,298,098
  3. Dexs: $195,688,277
  4. Launchpad: $154,488,317
  5. Chain: $117,703,341
  6. Prediction Market: $114,481,043
  7. Liquid Staking: $97,743,732
  8. Lending: $94,163,813
  9. Staking Pool: $70,614,382
  10. RWA: $68,995,235

Total fees by category saved to: data/processed/total_fees_by_category.json
Done

In [ ]:
# Test function to pull top n parent protocols by category
metrics = {
    'dailyFees': 'fees',
    'dailyRevenue': 'revenue',
    'dailyHoldersRevenue': 'holders-revenue',
    'tvl': 'tvl'
}

categories = ['Derivatives',
              'Dexs',
              'Launchpad',
              'Lending',
              'Liquid Staking',
              'Options',
              'Super App']

n = 10

results = data_processing.top_n_protocols_by_category_by_metric(
    metrics=metrics,
    n=n,
    categories=categories,
    defillama_output_dir=defillama_output_dir,
    window=window
)

Loading parent protocol categories from data/processed/parent_protocols.json...
Loaded 1642 parent protocol categories

Processing all metrics using established categories...
Processing fees...
Processing revenue...
Processing holders-revenue...
Processing tvl...

Final output saved to: data/processed/top_protocols_by_category_by_metric.json
Done

In [ ]:
# Pull time series data for top parent protocols by dailyFees

# Define which metrics to pull
metrics = {
    'dailyFees': 'fees',
    'dailyRevenue': 'revenue',
    'dailyHoldersRevenue': 'holders-revenue',
    'tvl': 'tvl'
}

data_processing.pull_top_parent_protocols_timeseries(metrics, defillama_output_dir)

Pulling 4 metric(s) for 55 parent protocols (top by dailyFees)
DefiLlama metric data: 6 fresh file(s) skipped, 214 to pull

DefiLlama metric data:   0%|          | 1/214 [00:00<01:05,  3.27pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/arcus?dataType=dailyHoldersRevenue

DefiLlama metric data:   5%|▌         | 11/214 [00:00<00:07, 25.49pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/antarctic?dataType=dailyHoldersRevenue

DefiLlama metric data:   7%|▋         | 16/214 [00:00<00:10, 18.54pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/astherus?dataType=dailyFees
  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/astherus?dataType=dailyHoldersRevenue

DefiLlama metric data:   9%|▉         | 20/214 [00:01<00:10, 17.92pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/binance-staked-eth?dataType=dailyHoldersRevenue
  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/protocol/astherus
  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/astherus?dataType=dailyRevenue

DefiLlama metric data:  14%|█▎        | 29/214 [00:01<00:08, 22.94pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/binance-staked-sol?dataType=dailyHoldersRevenue
  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/callput?dataType=dailyHoldersRevenue

DefiLlama metric data:  15%|█▌        | 33/214 [00:02<00:12, 14.23pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/coinbase-wrapped-staked-eth?dataType=dailyHoldersRevenue  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/circle?dataType=dailyHoldersRevenue

DefiLlama metric data:  22%|██▏       | 47/214 [00:03<00:13, 11.96pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/decibel?dataType=dailyHoldersRevenue
  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/dolomite?dataType=dailyHoldersRevenue

DefiLlama metric data:  25%|██▌       | 54/214 [00:04<00:22,  7.21pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/dream?dataType=dailyHoldersRevenue

DefiLlama metric data:  30%|███       | 65/214 [00:05<00:15,  9.35pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/extended?dataType=dailyHoldersRevenue

DefiLlama metric data:  33%|███▎      | 71/214 [00:06<00:16,  8.87pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/fables?dataType=dailyHoldersRevenue
  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/extended?dataType=dailyRevenue

DefiLlama metric data:  38%|███▊      | 81/214 [00:06<00:10, 12.52pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/fomo?dataType=dailyHoldersRevenue

DefiLlama metric data:  40%|███▉      | 85/214 [00:07<00:12, 10.53pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/forward-industries-sol?dataType=dailyHoldersRevenue

DefiLlama metric data:  50%|█████     | 107/214 [00:09<00:10,  9.74pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/liquid-collective?dataType=dailyHoldersRevenue

DefiLlama metric data:  53%|█████▎    | 114/214 [00:10<00:08, 12.48pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/protocol/maker
  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/maker?dataType=dailyFees
  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/maker?dataType=dailyRevenue
  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/maker?dataType=dailyHoldersRevenue

DefiLlama metric data:  64%|██████▎   | 136/214 [00:12<00:07,  9.79pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/pacifica?dataType=dailyHoldersRevenue
  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/panoptic?dataType=dailyRevenue

DefiLlama metric data:  67%|██████▋   | 144/214 [00:13<00:05, 13.31pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/panoptic?dataType=dailyHoldersRevenue  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/panoptic?dataType=dailyFees

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/protocol/panoptic

DefiLlama metric data:  68%|██████▊   | 146/214 [00:13<00:06, 10.27pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/project-x?dataType=dailyHoldersRevenue

DefiLlama metric data:  75%|███████▍  | 160/214 [00:15<00:07,  6.91pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/protocol/ramses-exchange-hl

DefiLlama metric data:  76%|███████▌  | 163/214 [00:16<00:10,  4.97pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/sofa.org?dataType=dailyHoldersRevenue
  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/rocket-pool?dataType=dailyHoldersRevenue

DefiLlama metric data:  83%|████████▎ | 177/214 [00:17<00:02, 14.28pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/stochastic-finance?dataType=dailyHoldersRevenue

DefiLlama metric data:  85%|████████▍ | 181/214 [00:18<00:03,  9.80pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/tonstakers?dataType=dailyHoldersRevenue

DefiLlama metric data:  93%|█████████▎| 198/214 [00:19<00:01, 11.00pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/venus-finance?dataType=dailyFees

DefiLlama metric data:  93%|█████████▎| 200/214 [00:20<00:01,  9.55pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/venus-finance?dataType=dailyHoldersRevenue

DefiLlama metric data:  97%|█████████▋| 207/214 [00:21<00:01,  6.71pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/txflow?dataType=dailyHoldersRevenue

DefiLlama metric data:  97%|█████████▋| 208/214 [00:21<00:01,  5.81pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/venus-finance?dataType=dailyRevenue

DefiLlama metric data:  99%|█████████▉| 212/214 [00:23<00:00,  2.14pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/protocol/venus-finance

DefiLlama metric data: 100%|██████████| 214/214 [00:44<00:00,  4.76pull/s]

Missing data by metric:
  fees: 4 of 55 protocols missing
    - astherus
    - maker
    - panoptic
    - venus-finance
  revenue: 5 of 55 protocols missing
    - astherus
    - extended
    - maker
    - panoptic
    - venus-finance
  holders-revenue: 26 of 55 protocols missing
    - antarctic
    - arcus
    - astherus
    - binance-staked-eth
    - binance-staked-sol
    - callput
    - circle
    - coinbase-wrapped-staked-eth
    - decibel
    - dolomite
    - dream
    - extended
    - fables
    - fomo
    - forward-industries-sol
    - liquid-collective
    - maker
    - pacifica
    - panoptic
    - project-x
    - rocket-pool
    - sofa.org
    - stochastic-finance
    - tonstakers
    - txflow
    - venus-finance
  tvl: 5 of 55 protocols missing
    - astherus
    - maker
    - panoptic
    - ramses-exchange-hl
    - venus-finance

In [ ]:
# Load parameters for following functions
start_date = '2021-01-01'  # Start date for the data (format: 'YYYY-MM-DD')
parent_categories_path = 'data/processed/parent_protocols.json'
top_protocols_path = 'data/processed/top_protocols_by_category_by_metric.json'
defillama_output_dir = 'data/raw/defillama'

In [ ]:
# Test function to calculate gross margins by category
category_gross_margins = data_processing.category_gross_margin_comparison(
    start_date=start_date,
    parent_categories_path=parent_categories_path,
    top_protocols_path=top_protocols_path,
    defillama_output_dir=defillama_output_dir
)

print(category_gross_margins.tail())

Found 55 top parent protocols with fees data
Found categories: {'Lending', 'Options', 'Super App', 'Derivatives', 'Dexs', 'Liquid Staking'}

Processing category: Lending
  Found 10 parent protocols in Lending
  Processing parent: aave
    aave avg gross margin: 13.53%
  Processing parent: hyperlend
    hyperlend avg gross margin: 16.10%
  Processing parent: dolomite
    dolomite avg gross margin: 20.21%
  Processing parent: euler
    euler avg gross margin: 5.32%
  Processing parent: venus-finance
    Warning: data/raw/defillama/fees/venus-finance.json not found, attempting to pull data

DefiLlama metric data:   0%|          | 0/1 [00:00<?, ?pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/venus-finance?dataType=dailyFees

DefiLlama metric data: 100%|██████████| 1/1 [00:00<00:00, 16.36pull/s]

All fees data saved to data/raw/defillama/fees/

Failed to pull (1):
  fees:
    - venus-finance
    Failed to pull fees data for venus-finance, skipping this parent
    Skipping venus-finance - incomplete data
  Processing parent: maple-finance
    maple-finance avg gross margin: 13.36%
  Processing parent: world-liberty-financial
    world-liberty-financial avg gross margin: 100.00%
  Processing parent: compound-finance
    compound-finance avg gross margin: 11.48%
  Processing parent: morpho
    morpho avg gross margin: 0.00%
  Processing parent: justlend
    justlend avg gross margin: 5.22%
  Found 9 parent fee columns and 9 parent revenue columns
  Category Lending processed successfully

Processing category: Options
  Found 5 parent protocols in Options
  Processing parent: panoptic
    Warning: data/raw/defillama/fees/panoptic.json not found, attempting to pull data

DefiLlama metric data:   0%|          | 0/1 [00:00<?, ?pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/panoptic?dataType=dailyFees

DefiLlama metric data: 100%|██████████| 1/1 [00:00<00:00, 38.17pull/s]

All fees data saved to data/raw/defillama/fees/

Failed to pull (1):
  fees:
    - panoptic
    Failed to pull fees data for panoptic, skipping this parent
    Skipping panoptic - incomplete data
  Processing parent: sofa.org
    sofa.org avg gross margin: 100.00%
  Processing parent: callput
    callput avg gross margin: 100.00%
  Processing parent: dream
    dream avg gross margin: 99.50%
  Processing parent: stochastic-finance
    stochastic-finance avg gross margin: 100.00%
  Found 4 parent fee columns and 4 parent revenue columns
  Category Options processed successfully

Processing category: Super App
  Found 10 parent protocols in Super App
  Processing parent: fomo
    fomo avg gross margin: 92.97%
  Processing parent: circle
    circle avg gross margin: 99.87%
  Processing parent: pump
    pump avg gross margin: 59.49%
  Processing parent: hyperliquid
    hyperliquid avg gross margin: 80.93%
  Processing parent: spark
    spark avg gross margin: 6.46%
  Processing parent: jupiter
    jupiter avg gross margin: 32.62%
  Processing parent: maker
    Warning: data/raw/defillama/fees/maker.json not found, attempting to pull data

DefiLlama metric data: 100%|██████████| 1/1 [00:00<00:00, 54.18pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/maker?dataType=dailyFees

All fees data saved to data/raw/defillama/fees/

Failed to pull (1):
  fees:
    - maker
    Failed to pull fees data for maker, skipping this parent
    Skipping maker - incomplete data
  Processing parent: axiom
    axiom avg gross margin: 60.43%
  Processing parent: meteora
    meteora avg gross margin: 5.17%
  Processing parent: raydium
    raydium avg gross margin: 10.09%
  Found 9 parent fee columns and 9 parent revenue columns
  Category Super App processed successfully

Processing category: Derivatives
  Found 10 parent protocols in Derivatives
  Processing parent: gmx
    gmx avg gross margin: 32.25%
  Processing parent: pacifica
    pacifica avg gross margin: 99.05%
  Processing parent: antarctic
    antarctic avg gross margin: 13.18%
  Processing parent: gains-network
    gains-network avg gross margin: 74.36%

  Processing parent: astherus
    Warning: data/raw/defillama/fees/astherus.json not found, attempting to pull data

DefiLlama metric data:   0%|          | 0/1 [00:00<?, ?pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/astherus?dataType=dailyFees

DefiLlama metric data: 100%|██████████| 1/1 [00:00<00:00, 19.72pull/s]

All fees data saved to data/raw/defillama/fees/

Failed to pull (1):
  fees:
    - astherus
    Failed to pull fees data for astherus, skipping this parent
    Skipping astherus - incomplete data
  Processing parent: decibel
    decibel avg gross margin: 100.00%
  Processing parent: edgex
    edgex avg gross margin: 74.55%
  Processing parent: arcus
    arcus avg gross margin: 91.56%
  Processing parent: txflow
    txflow avg gross margin: 100.00%
  Processing parent: extended
    Warning: data/raw/defillama/revenue/extended.json not found, attempting to pull data

DefiLlama metric data: 100%|██████████| 1/1 [00:00<00:00, 20.01pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/extended?dataType=dailyRevenue

All revenue data saved to data/raw/defillama/revenue/

Failed to pull (1):
  revenue:
    - extended
    Failed to pull revenue data for extended, skipping this parent
    Skipping extended - incomplete data
  Found 8 parent fee columns and 8 parent revenue columns
  Category Derivatives processed successfully

Processing category: Dexs
  Found 10 parent protocols in Dexs
  Processing parent: project-x

    project-x avg gross margin: 14.30%
  Processing parent: uniswap
    uniswap avg gross margin: 0.92%
  Processing parent: ramses-exchange-hl
    ramses-exchange-hl avg gross margin: 84.66%
  Processing parent: thorchain-dex
    thorchain-dex avg gross margin: 5.34%
  Processing parent: up
    up avg gross margin: 69.27%
  Processing parent: aerodrome
    aerodrome avg gross margin: 87.33%
  Processing parent: fables
    fables avg gross margin: 0.00%
  Processing parent: pharaoh-exchange
    pharaoh-exchange avg gross margin: 98.90%
  Processing parent: orca
    orca avg gross margin: 11.51%
  Processing parent: chainflip
    chainflip avg gross margin: 22.62%
  Found 10 parent fee columns and 10 parent revenue columns
  Category Dexs processed successfully

Processing category: Liquid Staking
  Found 10 parent protocols in Liquid Staking
  Processing parent: rocket-pool
    rocket-pool avg gross margin: 0.00%
  Processing parent: tonstakers
    tonstakers avg gross margin: 16.00%
  Processing parent: binance-staked-sol
    binance-staked-sol avg gross margin: 21.13%
  Processing parent: lido
    lido avg gross margin: 5.12%
  Processing parent: coinbase-wrapped-staked-eth
    coinbase-wrapped-staked-eth avg gross margin: 10.00%
  Processing parent: liquid-collective
    liquid-collective avg gross margin: 10.00%
  Processing parent: forward-industries-sol
    forward-industries-sol avg gross margin: 2.46%
  Processing parent: meth-protocol
    meth-protocol avg gross margin: 10.00%
  Processing parent: binance-staked-eth
    binance-staked-eth avg gross margin: 10.00%
  Processing parent: drift
    drift avg gross margin: 46.52%
  Found 10 parent fee columns and 10 parent revenue columns
  Category Liquid Staking processed successfully

Gross margins by parent category saved to: data/processed/financial-metrics\gross-margins-by-category.json

Category-level aggregate gross margins (first 5 dates):

2021-01-01T00:00:00:
  Lending: 0.1055
  Options: nan
  Super App: nan
  Derivatives: nan
  Dexs: 0.0000
  Liquid Staking: nan

2021-01-02T00:00:00:
  Lending: 0.1071
  Options: nan
  Super App: nan
  Derivatives: nan
  Dexs: 0.0000
  Liquid Staking: nan

2021-01-03T00:00:00:
  Lending: 0.1081
  Options: nan
  Super App: nan
  Derivatives: nan
  Dexs: 0.0000
  Liquid Staking: nan

2021-01-04T00:00:00:
  Lending: 0.1097
  Options: nan
  Super App: nan
  Derivatives: nan
  Dexs: 0.0000
  Liquid Staking: nan

2021-01-05T00:00:00:
  Lending: 0.1112
  Options: nan
  Super App: nan
  Derivatives: nan
  Dexs: 0.0000
  Liquid Staking: nan
           date  Lending-gross-margin-30d  Options-gross-margin-30d  \
2892 2026-10-05                  0.222567                  1.000000
2893 2026-10-06                  0.222484                  1.000000
2894 2026-10-07                  0.221575                  1.000000
2895 2026-10-08                  0.220878                  1.000000
2896 2026-10-09                  0.220892                  0.999337

      Super App-gross-margin-30d  Derivatives-gross-margin-30d  \
2892                    0.609173                      0.647975
2893                    0.608785                      0.647544
2894                    0.608727                      0.647739
2895                    0.608642                      0.649989
2896                    0.608529                      0.652578

      Dexs-gross-margin-30d  Liquid Staking-gross-margin-30d
2892               0.148857                         0.074471
2893               0.150688                         0.074350
2894               0.152850                         0.074396
2895               0.154943                         0.074427
2896               0.142831                         0.074615

In [ ]:
# Test function to calculate fees to tvl comparison
category_fees_vs_tvl = data_processing.category_fees_to_tvl_comparison(
    start_date=start_date,
    parent_categories_path=parent_categories_path,
    top_protocols_path=top_protocols_path,
    defillama_output_dir=defillama_output_dir
)

print(category_fees_vs_tvl.tail())

# Test function to calculate revenue to tvl comparison
category_revenue_vs_tvl = data_processing.category_revenue_to_tvl_comparison(
    start_date=start_date,
    parent_categories_path=parent_categories_path,
    top_protocols_path=top_protocols_path,
    defillama_output_dir=defillama_output_dir
)

print(category_revenue_vs_tvl.tail())

Found 55 top parent protocols with fees data
Found categories: {'Lending', 'Options', 'Super App', 'Derivatives', 'Dexs', 'Liquid Staking'}

Processing category: Lending
  Found 10 parent protocols in Lending
  Processing parent: aave
    aave avg fees/TVL: 1.20%
  Processing parent: hyperlend
    hyperlend avg fees/TVL: 1.15%
  Processing parent: dolomite
    dolomite avg fees/TVL: 1.73%
  Processing parent: euler
    euler avg fees/TVL: 1.87%
  Processing parent: venus-finance
    Warning: data/raw/defillama/fees/venus-finance.json not found, attempting to pull data

DefiLlama metric data: 100%|██████████| 1/1 [00:00<00:00, 21.68pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/venus-finance?dataType=dailyFees

All fees data saved to data/raw/defillama/fees/

Failed to pull (1):
  fees:
    - venus-finance
    Failed to pull fees data for venus-finance
    Warning: data/raw/defillama/tvl/venus-finance.json not found, attempting to pull data

DefiLlama metric data: 100%|██████████| 1/1 [00:00<00:00, 41.14pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/protocol/venus-finance

All tvl data saved to data/raw/defillama/tvl/

Failed to pull (1):
  tvl:
    - venus-finance
    Failed to pull TVL data for venus-finance
    No fees data for parent venus-finance, skipping
  Processing parent: maple-finance
    maple-finance avg fees/TVL: 1.98%
  Processing parent: world-liberty-financial

    Error loading TVL from data/raw/defillama/tvl/world-liberty-financial.json: 'date'
    No TVL data for parent world-liberty-financial, skipping
  Processing parent: compound-finance
    compound-finance avg fees/TVL: 1.27%
  Processing parent: morpho
    morpho avg fees/TVL: 1.32%
  Processing parent: justlend
    justlend avg fees/TVL: 0.11%
  Found 8 parent fee columns and 8 parent TVL columns
  Category Lending processed successfully

Processing category: Options
  Found 5 parent protocols in Options
  Processing parent: panoptic
    Warning: data/raw/defillama/fees/panoptic.json not found, attempting to pull data

DefiLlama metric data: 100%|██████████| 1/1 [00:00<00:00, 54.96pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/panoptic?dataType=dailyFees

All fees data saved to data/raw/defillama/fees/

Failed to pull (1):
  fees:
    - panoptic
    Failed to pull fees data for panoptic
    Warning: data/raw/defillama/tvl/panoptic.json not found, attempting to pull data

DefiLlama metric data: 100%|██████████| 1/1 [00:00<00:00, 57.77pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/protocol/panoptic

All tvl data saved to data/raw/defillama/tvl/

Failed to pull (1):
  tvl:
    - panoptic
    Failed to pull TVL data for panoptic
    No fees data for parent panoptic, skipping
  Processing parent: sofa.org

    sofa.org avg fees/TVL: 4.33%
  Processing parent: callput
    callput avg fees/TVL: 73.53%
  Processing parent: dream
    Error loading TVL from data/raw/defillama/tvl/dream.json: 'date'
    No TVL data for parent dream, skipping
  Processing parent: stochastic-finance
    stochastic-finance avg fees/TVL: 24.35%
  Found 3 parent fee columns and 3 parent TVL columns
  Category Options processed successfully

Processing category: Super App
  Found 10 parent protocols in Super App
  Processing parent: fomo
    Error loading TVL from data/raw/defillama/tvl/fomo.json: 'date'
    No TVL data for parent fomo, skipping
  Processing parent: circle
    Error loading TVL from data/raw/defillama/tvl/circle.json: 'date'
    No TVL data for parent circle, skipping
  Processing parent: pump
    pump avg fees/TVL: 680.03%
  Processing parent: hyperliquid
    hyperliquid avg fees/TVL: 19.13%
  Processing parent: spark
    spark avg fees/TVL: 1.72%
  Processing parent: jupiter
    jupiter avg fees/TVL: 18.32%
  Processing parent: maker
    Warning: data/raw/defillama/fees/maker.json not found, attempting to pull data

DefiLlama metric data: 100%|██████████| 1/1 [00:00<00:00, 54.12pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/maker?dataType=dailyFees

All fees data saved to data/raw/defillama/fees/

Failed to pull (1):
  fees:
    - maker
    Failed to pull fees data for maker
    Warning: data/raw/defillama/tvl/maker.json not found, attempting to pull data

DefiLlama metric data: 100%|██████████| 1/1 [00:00<00:00, 51.81pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/protocol/maker

All tvl data saved to data/raw/defillama/tvl/

Failed to pull (1):
  tvl:
    - maker
    Failed to pull TVL data for maker
    No fees data for parent maker, skipping
  Processing parent: axiom
    Error loading TVL from data/raw/defillama/tvl/axiom.json: 'date'
    No TVL data for parent axiom, skipping
  Processing parent: meteora
    meteora avg fees/TVL: 101.58%
  Processing parent: raydium

    Error loading TVL from data/raw/defillama/tvl/raydium.json: 'date'
    No TVL data for parent raydium, skipping
  Found 5 parent fee columns and 5 parent TVL columns
  Category Super App processed successfully

Processing category: Derivatives
  Found 10 parent protocols in Derivatives
  Processing parent: gmx
    gmx avg fees/TVL: 11.90%
  Processing parent: pacifica
    pacifica avg fees/TVL: 27.78%
  Processing parent: antarctic
    antarctic avg fees/TVL: 565.78%
  Processing parent: gains-network
    gains-network avg fees/TVL: 11.81%
  Processing parent: astherus
    Warning: data/raw/defillama/fees/astherus.json not found, attempting to pull data

DefiLlama metric data: 100%|██████████| 1/1 [00:00<00:00, 26.30pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/astherus?dataType=dailyFees

All fees data saved to data/raw/defillama/fees/

Failed to pull (1):
  fees:
    - astherus
    Failed to pull fees data for astherus
    Warning: data/raw/defillama/tvl/astherus.json not found, attempting to pull data

DefiLlama metric data: 100%|██████████| 1/1 [00:00<00:00,  9.31pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/protocol/astherus

All tvl data saved to data/raw/defillama/tvl/

Failed to pull (1):
  tvl:
    - astherus
    Failed to pull TVL data for astherus
    No fees data for parent astherus, skipping
  Processing parent: decibel
    decibel avg fees/TVL: 14.40%

  Processing parent: edgex
    edgex avg fees/TVL: 188.83%
  Processing parent: arcus
    arcus avg fees/TVL: 28.59%
  Processing parent: txflow
    Error loading TVL from data/raw/defillama/tvl/txflow.json: 'date'
    No TVL data for parent txflow, skipping
  Processing parent: extended
    extended avg fees/TVL: 21.71%
  Found 8 parent fee columns and 8 parent TVL columns
  Category Derivatives processed successfully

Processing category: Dexs
  Found 10 parent protocols in Dexs
  Processing parent: project-x
    project-x avg fees/TVL: 64.54%
  Processing parent: uniswap
    uniswap avg fees/TVL: 20.34%
  Processing parent: ramses-exchange-hl
    Warning: data/raw/defillama/tvl/ramses-exchange-hl.json not found, attempting to pull data

DefiLlama metric data: 100%|██████████| 1/1 [00:00<00:00, 48.07pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/protocol/ramses-exchange-hl

All tvl data saved to data/raw/defillama/tvl/

Failed to pull (1):
  tvl:
    - ramses-exchange-hl
    Failed to pull TVL data for ramses-exchange-hl
    No TVL data for parent ramses-exchange-hl, skipping
  Processing parent: thorchain-dex

    thorchain-dex avg fees/TVL: 20.50%
  Processing parent: up
    up avg fees/TVL: 301.55%
  Processing parent: aerodrome
    aerodrome avg fees/TVL: 37.38%
  Processing parent: fables
    fables avg fees/TVL: 157.21%
  Processing parent: pharaoh-exchange
    pharaoh-exchange avg fees/TVL: 33.67%
  Processing parent: orca
    orca avg fees/TVL: 17.24%
  Processing parent: chainflip
    chainflip avg fees/TVL: 7.22%
  Found 9 parent fee columns and 9 parent TVL columns
  Category Dexs processed successfully

Processing category: Liquid Staking
  Found 10 parent protocols in Liquid Staking
  Processing parent: rocket-pool
    rocket-pool avg fees/TVL: 2.59%
  Processing parent: tonstakers
    tonstakers avg fees/TVL: 3.75%
  Processing parent: binance-staked-sol
    binance-staked-sol avg fees/TVL: 6.97%
  Processing parent: lido
    lido avg fees/TVL: 3.39%
  Processing parent: coinbase-wrapped-staked-eth
    coinbase-wrapped-staked-eth avg fees/TVL: 4.51%
  Processing parent: liquid-collective
    liquid-collective avg fees/TVL: 2.65%
  Processing parent: forward-industries-sol
    forward-industries-sol avg fees/TVL: 92.44%
  Processing parent: meth-protocol
    meth-protocol avg fees/TVL: 3.86%
  Processing parent: binance-staked-eth
    binance-staked-eth avg fees/TVL: 2.91%
  Processing parent: drift
    drift avg fees/TVL: 3.91%
  Found 10 parent fee columns and 10 parent TVL columns
  Category Liquid Staking processed successfully

Fees to TVL ratios by parent category saved to: data/processed/financial-metrics\fees-to-tvl-by-category.json

Category-level aggregate fees/TVL ratios (first 5 dates):

2021-01-01T00:00:00:
  Lending: 0.0146
  Options: nan
  Super App: nan
  Derivatives: nan
  Dexs: 0.2492
  Liquid Staking: nan

2021-01-01T23:00:00:
  Lending: 0.0146
  Options: nan
  Super App: nan
  Derivatives: nan
  Dexs: 0.2492
  Liquid Staking: 0.0000

2021-01-02T00:00:00:
  Lending: 0.0152
  Options: nan
  Super App: nan
  Derivatives: nan
  Dexs: 0.2518
  Liquid Staking: 0.0000

2021-01-02T23:00:00:
  Lending: 0.0152
  Options: nan
  Super App: nan
  Derivatives: nan
  Dexs: 0.2518
  Liquid Staking: 0.0000

2021-01-03T00:00:00:
  Lending: 0.0158
  Options: nan
  Super App: nan
  Derivatives: nan
  Dexs: 0.2577
  Liquid Staking: 0.0000
                    date  Lending-fees-to-tvl-30d  Options-fees-to-tvl-30d  \
3107 2026-10-10 13:39:11                 0.008008                 0.051581
3108 2026-10-10 13:40:11                 0.008008                 0.051581
3109 2026-10-10 13:41:11                 0.007611                 0.051581
3110 2026-10-10 13:42:11                 0.007611                 0.051581
3111 2026-10-10 13:43:11                 0.007611                 0.051581

      Super App-fees-to-tvl-30d  Derivatives-fees-to-tvl-30d  \
3107                   0.155053                     0.282311
3108                   0.155053                     0.282311
3109                   0.155053                     0.282311
3110                   0.155053                     0.266009
3111                   0.149234                     0.266009

      Dexs-fees-to-tvl-30d  Liquid Staking-fees-to-tvl-30d
3107              0.277677                        0.017929
3108              0.277677                        0.017042
3109              0.277677                        0.017042
3110              0.277677                        0.017042
3111              0.277677                        0.017042
Found 55 top parent protocols with revenue data
Found categories: {'Lending', 'Options', 'Super App', 'Derivatives', 'Dexs', 'Liquid Staking'}

Processing category: Lending
  Found 10 parent protocols in Lending
  Processing parent: aave
    aave avg revenue/TVL: 0.16%
  Processing parent: resupply
    Warning: data/raw/defillama/revenue/resupply.json not found, attempting to pull data

DefiLlama metric data: 100%|██████████| 1/1 [00:02<00:00,  2.34s/pull]

All revenue data saved to data/raw/defillama/revenue/
    Warning: data/raw/defillama/tvl/resupply.json not found, attempting to pull data

DefiLlama metric data: 100%|██████████| 1/1 [00:00<00:00,  2.19pull/s]

All tvl data saved to data/raw/defillama/tvl/
    resupply avg revenue/TVL: 2.89%
  Processing parent: dolomite
    dolomite avg revenue/TVL: 0.35%
  Processing parent: euler
    euler avg revenue/TVL: 0.10%
  Processing parent: venus-finance
    Warning: data/raw/defillama/revenue/venus-finance.json not found, attempting to pull data

DefiLlama metric data: 100%|██████████| 1/1 [00:00<00:00, 23.59pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/venus-finance?dataType=dailyRevenue

All revenue data saved to data/raw/defillama/revenue/

Failed to pull (1):
  revenue:
    - venus-finance
    Failed to pull revenue data for venus-finance
    Warning: data/raw/defillama/tvl/venus-finance.json not found, attempting to pull data

DefiLlama metric data: 100%|██████████| 1/1 [00:00<00:00, 27.74pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/protocol/venus-finance

All tvl data saved to data/raw/defillama/tvl/

Failed to pull (1):
  tvl:
    - venus-finance
    Failed to pull TVL data for venus-finance
    No revenue data for parent venus-finance, skipping
  Processing parent: maple-finance
    maple-finance avg revenue/TVL: 0.26%

  Processing parent: world-liberty-financial
    Error loading TVL from data/raw/defillama/tvl/world-liberty-financial.json: 'date'
    No TVL data for parent world-liberty-financial, skipping
  Processing parent: shoebill-finance
    Warning: data/raw/defillama/revenue/shoebill-finance.json not found, attempting to pull data

DefiLlama metric data: 100%|██████████| 1/1 [00:00<00:00,  1.34pull/s]

All revenue data saved to data/raw/defillama/revenue/
    Warning: data/raw/defillama/tvl/shoebill-finance.json not found, attempting to pull data

DefiLlama metric data: 100%|██████████| 1/1 [00:02<00:00,  2.23s/pull]

All tvl data saved to data/raw/defillama/tvl/
    shoebill-finance avg revenue/TVL: 0.64%
  Processing parent: compound-finance
    compound-finance avg revenue/TVL: 0.15%
  Processing parent: hyperlend
    hyperlend avg revenue/TVL: 0.19%
  Found 8 parent revenue columns and 8 parent TVL columns
  Category Lending processed successfully

Processing category: Options
  Found 5 parent protocols in Options
  Processing parent: panoptic
    Warning: data/raw/defillama/revenue/panoptic.json not found, attempting to pull data

DefiLlama metric data: 100%|██████████| 1/1 [00:00<00:00, 35.05pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/panoptic?dataType=dailyRevenue

All revenue data saved to data/raw/defillama/revenue/

Failed to pull (1):
  revenue:
    - panoptic
    Failed to pull revenue data for panoptic
    Warning: data/raw/defillama/tvl/panoptic.json not found, attempting to pull data

DefiLlama metric data: 100%|██████████| 1/1 [00:00<00:00, 48.84pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/protocol/panoptic

All tvl data saved to data/raw/defillama/tvl/

Failed to pull (1):
  tvl:
    - panoptic
    Failed to pull TVL data for panoptic
    No revenue data for parent panoptic, skipping
  Processing parent: sofa.org

    sofa.org avg revenue/TVL: 4.33%
  Processing parent: callput
    callput avg revenue/TVL: 73.53%
  Processing parent: dream
    Error loading TVL from data/raw/defillama/tvl/dream.json: 'date'
    No TVL data for parent dream, skipping
  Processing parent: stochastic-finance
    stochastic-finance avg revenue/TVL: 24.35%
  Found 3 parent revenue columns and 3 parent TVL columns
  Category Options processed successfully

Processing category: Super App
  Found 10 parent protocols in Super App
  Processing parent: fomo
    Error loading TVL from data/raw/defillama/tvl/fomo.json: 'date'
    No TVL data for parent fomo, skipping
  Processing parent: pancakeswap
    Warning: data/raw/defillama/revenue/pancakeswap.json not found, attempting to pull data

DefiLlama metric data: 100%|██████████| 1/1 [00:00<00:00,  1.29pull/s]

All revenue data saved to data/raw/defillama/revenue/
    Warning: data/raw/defillama/tvl/pancakeswap.json not found, attempting to pull data

DefiLlama metric data: 100%|██████████| 1/1 [00:00<00:00,  1.08pull/s]

All tvl data saved to data/raw/defillama/tvl/
    pancakeswap avg revenue/TVL: 2.20%
  Processing parent: circle
    Error loading TVL from data/raw/defillama/tvl/circle.json: 'date'
    No TVL data for parent circle, skipping
  Processing parent: pump
    pump avg revenue/TVL: 404.55%
  Processing parent: hyperliquid
    hyperliquid avg revenue/TVL: 15.48%
  Processing parent: phantom
    Warning: data/raw/defillama/revenue/phantom.json not found, attempting to pull data

DefiLlama metric data: 100%|██████████| 1/1 [00:00<00:00,  1.59pull/s]

All revenue data saved to data/raw/defillama/revenue/
    Warning: data/raw/defillama/tvl/phantom.json not found, attempting to pull data

DefiLlama metric data: 100%|██████████| 1/1 [00:00<00:00,  2.74pull/s]

All tvl data saved to data/raw/defillama/tvl/
    Error loading TVL from data/raw/defillama/tvl/phantom.json: 'date'
    No TVL data for parent phantom, skipping
  Processing parent: jupiter
    jupiter avg revenue/TVL: 5.98%
  Processing parent: maker
    Warning: data/raw/defillama/revenue/maker.json not found, attempting to pull data

DefiLlama metric data: 100%|██████████| 1/1 [00:00<00:00, 49.42pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/maker?dataType=dailyRevenue

All revenue data saved to data/raw/defillama/revenue/

Failed to pull (1):
  revenue:
    - maker
    Failed to pull revenue data for maker
    Warning: data/raw/defillama/tvl/maker.json not found, attempting to pull data

DefiLlama metric data: 100%|██████████| 1/1 [00:00<00:00, 49.07pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/protocol/maker

All tvl data saved to data/raw/defillama/tvl/

Failed to pull (1):
  tvl:
    - maker
    Failed to pull TVL data for maker
    No revenue data for parent maker, skipping
  Processing parent: axiom
    Error loading TVL from data/raw/defillama/tvl/axiom.json: 'date'
    No TVL data for parent axiom, skipping
  Processing parent: raydium
    Error loading TVL from data/raw/defillama/tvl/raydium.json: 'date'
    No TVL data for parent raydium, skipping
  Found 4 parent revenue columns and 4 parent TVL columns
  Category Super App processed successfully

Processing category: Derivatives
  Found 10 parent protocols in Derivatives
  Processing parent: gmx
    gmx avg revenue/TVL: 3.84%
  Processing parent: primit
    Warning: data/raw/defillama/revenue/primit.json not found, attempting to pull data

DefiLlama metric data: 100%|██████████| 1/1 [00:00<00:00,  2.15pull/s]

All revenue data saved to data/raw/defillama/revenue/
    Warning: data/raw/defillama/tvl/primit.json not found, attempting to pull data

DefiLlama metric data: 100%|██████████| 1/1 [00:00<00:00,  2.17pull/s]

All tvl data saved to data/raw/defillama/tvl/
    Error loading TVL from data/raw/defillama/tvl/primit.json: 'date'
    No TVL data for parent primit, skipping
  Processing parent: pacifica
    pacifica avg revenue/TVL: 27.52%
  Processing parent: antarctic
    antarctic avg revenue/TVL: 74.57%
  Processing parent: gains-network
    gains-network avg revenue/TVL: 8.78%
  Processing parent: decibel
    decibel avg revenue/TVL: 14.40%
  Processing parent: edgex
    edgex avg revenue/TVL: 140.76%
  Processing parent: arcus
    arcus avg revenue/TVL: 26.18%
  Processing parent: catapult-trade
    Warning: data/raw/defillama/revenue/catapult-trade.json not found, attempting to pull data

DefiLlama metric data: 100%|██████████| 1/1 [00:00<00:00,  1.70pull/s]

All revenue data saved to data/raw/defillama/revenue/
    Warning: data/raw/defillama/tvl/catapult-trade.json not found, attempting to pull data

DefiLlama metric data: 100%|██████████| 1/1 [00:00<00:00,  2.60pull/s]

All tvl data saved to data/raw/defillama/tvl/
    Error loading TVL from data/raw/defillama/tvl/catapult-trade.json: 'date'
    No TVL data for parent catapult-trade, skipping
  Processing parent: txflow
    Error loading TVL from data/raw/defillama/tvl/txflow.json: 'date'
    No TVL data for parent txflow, skipping
  Found 7 parent revenue columns and 7 parent TVL columns
  Category Derivatives processed successfully

Processing category: Dexs
  Found 10 parent protocols in Dexs
  Processing parent: nest
    Warning: data/raw/defillama/revenue/nest.json not found, attempting to pull data

DefiLlama metric data: 100%|██████████| 1/1 [00:00<00:00,  1.99pull/s]

All revenue data saved to data/raw/defillama/revenue/
    Warning: data/raw/defillama/tvl/nest.json not found, attempting to pull data

DefiLlama metric data: 100%|██████████| 1/1 [00:00<00:00,  1.67pull/s]

All tvl data saved to data/raw/defillama/tvl/
    nest avg revenue/TVL: 35.17%
  Processing parent: uniswap
    uniswap avg revenue/TVL: 0.19%
  Processing parent: hydrex
    Warning: data/raw/defillama/revenue/hydrex.json not found, attempting to pull data

DefiLlama metric data: 100%|██████████| 1/1 [00:00<00:00,  2.94pull/s]

All revenue data saved to data/raw/defillama/revenue/
    Warning: data/raw/defillama/tvl/hydrex.json not found, attempting to pull data

DefiLlama metric data: 100%|██████████| 1/1 [00:02<00:00,  2.13s/pull]

All tvl data saved to data/raw/defillama/tvl/
    hydrex avg revenue/TVL: 39.40%
  Processing parent: thorchain-dex
    thorchain-dex avg revenue/TVL: 1.10%
  Processing parent: ramses-exchange-hl
    Warning: data/raw/defillama/tvl/ramses-exchange-hl.json not found, attempting to pull data

DefiLlama metric data: 100%|██████████| 1/1 [00:00<00:00, 58.46pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/protocol/ramses-exchange-hl

All tvl data saved to data/raw/defillama/tvl/

Failed to pull (1):
  tvl:
    - ramses-exchange-hl
    Failed to pull TVL data for ramses-exchange-hl
    No TVL data for parent ramses-exchange-hl, skipping
  Processing parent: up
    up avg revenue/TVL: 208.89%
  Processing parent: aerodrome

    aerodrome avg revenue/TVL: 32.64%
  Processing parent: pharaoh-exchange
    pharaoh-exchange avg revenue/TVL: 33.29%
  Processing parent: velodrome
    Warning: data/raw/defillama/revenue/velodrome.json not found, attempting to pull data

DefiLlama metric data: 100%|██████████| 1/1 [00:00<00:00,  1.13pull/s]

All revenue data saved to data/raw/defillama/revenue/
    Warning: data/raw/defillama/tvl/velodrome.json not found, attempting to pull data

DefiLlama metric data: 100%|██████████| 1/1 [00:04<00:00,  4.17s/pull]

All tvl data saved to data/raw/defillama/tvl/
    velodrome avg revenue/TVL: 10.22%
  Processing parent: orca
    orca avg revenue/TVL: 1.98%
  Found 9 parent revenue columns and 9 parent TVL columns
  Category Dexs processed successfully

Processing category: Liquid Staking
  Found 10 parent protocols in Liquid Staking
  Processing parent: tonstakers
    tonstakers avg revenue/TVL: 0.60%
  Processing parent: binance-staked-sol
    binance-staked-sol avg revenue/TVL: 1.47%
  Processing parent: lido
    lido avg revenue/TVL: 0.17%
  Processing parent: coinbase-wrapped-staked-eth
    coinbase-wrapped-staked-eth avg revenue/TVL: 0.45%
  Processing parent: jpool
    Warning: data/raw/defillama/revenue/jpool.json not found, attempting to pull data

DefiLlama metric data: 100%|██████████| 1/1 [00:00<00:00,  4.47pull/s]

All revenue data saved to data/raw/defillama/revenue/
    Warning: data/raw/defillama/tvl/jpool.json not found, attempting to pull data

DefiLlama metric data: 100%|██████████| 1/1 [00:00<00:00,  1.35pull/s]

All tvl data saved to data/raw/defillama/tvl/
    jpool avg revenue/TVL: 0.38%
  Processing parent: liquid-collective
    liquid-collective avg revenue/TVL: 0.27%
  Processing parent: meth-protocol
    meth-protocol avg revenue/TVL: 0.39%
  Processing parent: stakee
    Warning: data/raw/defillama/revenue/stakee.json not found, attempting to pull data

DefiLlama metric data: 100%|██████████| 1/1 [00:00<00:00,  2.29pull/s]

All revenue data saved to data/raw/defillama/revenue/
    Warning: data/raw/defillama/tvl/stakee.json not found, attempting to pull data

DefiLlama metric data: 100%|██████████| 1/1 [00:00<00:00,  2.04pull/s]

All tvl data saved to data/raw/defillama/tvl/
    stakee avg revenue/TVL: 1.13%
  Processing parent: binance-staked-eth
    binance-staked-eth avg revenue/TVL: 0.29%
  Processing parent: stake.link
    Warning: data/raw/defillama/revenue/stake.link.json not found, attempting to pull data

DefiLlama metric data: 100%|██████████| 1/1 [00:00<00:00,  2.12pull/s]

All revenue data saved to data/raw/defillama/revenue/
    Warning: data/raw/defillama/tvl/stake.link.json not found, attempting to pull data

DefiLlama metric data: 100%|██████████| 1/1 [00:00<00:00,  1.10pull/s]

All tvl data saved to data/raw/defillama/tvl/
    stake.link avg revenue/TVL: 0.46%
  Found 10 parent revenue columns and 10 parent TVL columns
  Category Liquid Staking processed successfully

Revenue to TVL ratios by parent category saved to: data/processed/financial-metrics\revenue-to-tvl-by-category.json

Category-level aggregate revenue/TVL ratios (first 5 dates):

2021-01-01T00:00:00:
  Lending: 0.0016
  Options: nan
  Super App: nan
  Derivatives: nan
  Dexs: 0.0000
  Liquid Staking: nan

2021-01-01T23:00:00:
  Lending: 0.0016
  Options: nan
  Super App: nan
  Derivatives: nan
  Dexs: 0.0000
  Liquid Staking: 0.0000

2021-01-02T00:00:00:
  Lending: 0.0017
  Options: nan
  Super App: nan
  Derivatives: nan
  Dexs: 0.0000
  Liquid Staking: 0.0000

2021-01-02T23:00:00:
  Lending: 0.0017
  Options: nan
  Super App: nan
  Derivatives: nan
  Dexs: 0.0000
  Liquid Staking: 0.0000

2021-01-03T00:00:00:
  Lending: 0.0018
  Options: nan
  Super App: nan
  Derivatives: nan
  Dexs: 0.0000
  Liquid Staking: 0.0000
                    date  Lending-revenue-to-tvl-30d  \
3108 2026-10-10 13:39:11                    0.001153
3109 2026-10-10 13:40:11                    0.001153
3110 2026-10-10 13:41:11                    0.001095
3111 2026-10-10 13:42:11                    0.001095
3112 2026-10-10 13:43:11                    0.001095

      Options-revenue-to-tvl-30d  Super App-revenue-to-tvl-30d  \
3108                    0.051581                      0.116228
3109                    0.051581                      0.116228
3110                    0.051581                      0.116228
3111                    0.051581                      0.116228
3112                    0.051581                      0.113297

      Derivatives-revenue-to-tvl-30d  Dexs-revenue-to-tvl-30d  \
3108                        0.208908                 0.046215
3109                        0.208908                 0.046215
3110                        0.208908                 0.046215
3111                        0.200138                 0.046215
3112                        0.200138                 0.046215

      Liquid Staking-revenue-to-tvl-30d
3108                           0.001431
3109                           0.001361
3110                           0.001361
3111                           0.001361
3112                           0.001361

In [ ]:
# Test pulling OI data for all dexs function

defillama.pull_all_open_interest(defillama_output_dir)

# Forward-fill missing values and save back to file
output_path = f"{defillama_output_dir}/open-interest/all-dexs.json"
with open(output_path, 'r') as f:
    data = json.load(f)

data = helper_functions.ffill_chart_breakdown(data)

with open(output_path, 'w') as f:
    json.dump(data, f, indent=2)

All open-interest data saved to data/raw/defillama/open-interest/

In [ ]:
# Test pulling all stablecoins function

defillama.pull_all_stablecoins(defillama_output_dir)

All stablecoins data saved to data/raw/defillama/stablecoins/

In [ ]:
# Test pulling specific stablecoins function
assets = ['USDC', 'USDT', 'USDe', 'BUSD', 'PYUSD']

defillama.pull_specific_stablecoins(assets, defillama_output_dir)

DefiLlama stablecoins: 100%|██████████| 5/5 [00:11<00:00,  2.32s/pull]

All stablecoins data saved to data/raw/defillama/stablecoins/

In [ ]:
# Test pulling stablecoin supply by network
networks = ['solana']

defillama.stablecoin_supply_by_network(networks, defillama_output_dir)

DefiLlama stablecoin supply by network: 100%|██████████| 1/1 [00:00<00:00,  1.22pull/s]

All stablecoins data saved to data/raw/defillama/stablecoins/

In [ ]:
# Test pulling top stablecoins by peg mechanism function
n = 20
pegMechanism = 'crypto-backed'
excluded_assets = ['Dai']

defillama.top_n_stablecoins_by_mcap(n, pegMechanism, excluded_assets, defillama_output_dir)

Data saved to data/raw/defillama/stablecoins/top-crypto-backed-stablecoins-by-mcap.json
Done

(['Sky Dollar',
  'Ethena USDe',
  'Falcon USD',
  'USDD',
  'United Stables',
  'GHO',
  'Polymarket USD',
  'Multipli rwaUSDi',
  'USD.AI',
  'apxUSD',
  'Re Protocol reUSD',
  'crvUSD',
  'Binance Peg BUSD',
  'Solstice USX',
  'flexUSD',
  'Mustang Finance',
  'Avalon USDa',
  'River Stablecoin',
  'Astherus',
  'Dola'],
 {'USDS': 'Sky Dollar',
  'USDe': 'Ethena USDe',
  'USDf': 'Falcon USD',
  'USDD': 'USDD',
  'U': 'United Stables',
  'GHO': 'GHO',
  'pUSD': 'Polymarket USD',
  'rwaUSDi': 'Multipli rwaUSDi',
  'USDai': 'USD.AI',
  'apxUSD': 'apxUSD',
  'reUSD': 'Re Protocol reUSD',
  'crvUSD': 'crvUSD',
  'BUSD': 'Binance Peg BUSD',
  'USX': 'Solstice USX',
  'FLEXUSD': 'flexUSD',
  'MUST': 'Mustang Finance',
  'USDA': 'Avalon USDa',
  'satUSD': 'River Stablecoin',
  'USDF': 'Astherus',
  'DOLA': 'Dola'})

In [ ]:
# DUNE

In [ ]:
# Test function to pull Dune data
query_ids = {'4078266': 'weekly-perps-dex-volumes',
             '4552208': 'maple-xirr',
             '5597706': 'hyperliquid-daily-volume-by-coin',
             '4307695': 'hyperliquid-usdc-supply',
             '3700662': 'sky-collateral'}

dune.fetch_and_save_dune_data(dune_api_key, query_ids, dune_output_dir)

Dune queries:  60%|██████    | 3/5 [00:01<00:00,  2.14pull/s]

  request failed: HTTP 402 HTTPError: https://api.dune.com/api/v1/query/4552208/results
  request failed: HTTP 404 HTTPError: https://api.dune.com/api/v1/query/5597706/results

Dune queries: 100%|██████████| 5/5 [00:02<00:00,  1.97pull/s]

All data saved to data/raw/dune/

Failed to pull (2):
  - hyperliquid-daily-volume-by-coin
  - maple-xirr

In [ ]:
# UPDATE PROTOCOL INDEX

In [ ]:
# --- Keep the protocol index up to date -------------------------------------
# Register the protocols pulled by top_n_protocols_by_category_by_metric (the
# `results` dict above) in config/protocol_index.json, then auto-fill their
# Messari / Blockworks slugs. Only protocols that came out of that DefiLlama
# pull are added. Nothing else from the DefiLlama universe.
#
# Non-destructive: protocols already in the index are skipped, and slugs already
# set are left untouched. You can hand-edit config/protocol_index.json to fix
# anything the functions get wrong, and your edits will not be overwritten.
#
# Display names come from the DefiLlama parent protocol ("Uniswap", not
# "Uniswap V3"), via the `name` field establish_parent_protocols records in
# data/processed/parent_protocols.json. repair_parent_display_names reports
# any entry in the synced category still carrying a sub-protocol's name; it is
# run as a dry run here, so nothing is rewritten. To apply the reported fixes,
# run it once with dry_run=False (it only touches names that are exactly one of
# the parent's own sub-protocol names, never a hand-chosen name).

# Map each DefiLlama category label (the keys inside `results`) -> the
# standardized category key used in protocol_index.json. Add rows to sync more.
sync_categories = {'Dexs': 'dexs',
                   'Launchpad': 'launchpads',
                   'Options': 'options',
                   'Super App': 'super_app'}

for dl_category, std_category in sync_categories.items():
    # Merge the {slug: display_name} maps across all pulled metrics for this category
    protocols = {}
    for metric_block in results.values():
        protocols.update(metric_block.get(dl_category, {}))

    print(f'{std_category} ({len(protocols)} protocols):')
    pi.add_defillama_protocols(protocols, category=std_category)
    pi.repair_parent_display_names(category=std_category, dry_run=True)
    pi.populate_remaining_slugs(
        standard_names=list(protocols),
        sources=['messari', 'blockworks'],
        blockworks_api_key=blockworks_api_key,
    )
    print('---------------------------')
print('Protocol index synced')

dexs (18 protocols):
add_defillama_protocols: added 0, skipped 18
  skipped: ['uniswap', 'aerodrome', 'orca', 'fables', 'thorchain-dex', 'pharaoh-exchange', 'ramses-exchange-hl', 'project-x', 'chainflip', 'up', 'nest', 'hydrex', 'velodrome', 'vvs-finance', 'quickswap', 'pulsex', 'balancer', 'ring-protocol'] (already in index)
repair_parent_display_names (dry run): would change 0, kept 26
  Messari all-assets file not found (c:\Users\JamesEvans\OneDrive - Reciprocal Ventures\Documents\Research\dd-tools\data\raw\messari\all-assets.json); run messari.pull_all_assets first. Skipping Messari.
populate_remaining_slugs: processed 11 protocol(s); filled 0 messari_slug, 0 blockworks_slug
---------------------------
super_app (20 protocols):
add_defillama_protocols: added 14, skipped 6
  added:   ['circle', 'pump', 'raydium', 'axiom', 'meteora', 'fomo', 'maker', 'phantom', 'pancakeswap', 'chainlink', 'bonkfun', 'near-protocol', 'arbitrum-foundation', 'lista-dao']
  skipped: ['hyperliquid', 'jupiter', 'spark', 'lighter', 'ether-fi', 'sanctum'] (already in index)
repair_parent_display_names (dry run): would change 0, kept 14
  Messari all-assets file not found (c:\Users\JamesEvans\OneDrive - Reciprocal Ventures\Documents\Research\dd-tools\data\raw\messari\all-assets.json); run messari.pull_all_assets first. Skipping Messari.
populate_remaining_slugs: processed 19 protocol(s); filled 0 messari_slug, 16 blockworks_slug
---------------------------
Protocol index synced

In [ ]:
# FRED

In [ ]:
# Test function to pull US M2 supply
series_id = 'M2SL'

fred.pull_m2_money_supply( series_id, fred_api_key, fred_output_dir)

All data saved to data/raw/fred/

In [ ]:
# MESSARI
start_date = '2021-01-01'
end_date = datetime.datetime.today().strftime('%Y-%m-%d')

In [ ]:
messari.pull_all_assets(messari_api_key, messari_output_dir)

All data saved to data/raw/messari/

In [ ]:
# Test function to pull metrics by assets
assets = {'bitcoin': 'bitcoin',
         }

metrics = ['futures-open-interest',
           'futures-funding-rate',
           'futures-volume',
           'marketcap',
           'price',
           'supply'
          ]


messari.pull_asset_data(assets, metrics, start_date, end_date, messari_api_key, messari_output_dir)

Messari asset data: 100%|██████████| 6/6 [00:01<00:00,  4.19pull/s]

All futures-open-interest data saved to data/raw/messari/futures-open-interest/
All futures-funding-rate data saved to data/raw/messari/futures-funding-rate/
All futures-volume data saved to data/raw/messari/futures-volume/
All marketcap data saved to data/raw/messari/marketcap/
All price data saved to data/raw/messari/price/
All supply data saved to data/raw/messari/supply/

In [ ]:
# Test function to save down all networks tracked by Messari's API then save save to a dictionary to be used in the pull_network_data function

metric_category = 'ecosystem'
metric_extract = 'ecosystemCommits24Hour'
excluded_slugs = []
n = 20
extract_dict = messari.fetch_and_save_top_n_networks(metric_category, metric_extract, excluded_slugs, n, messari_api_key, messari_output_dir)

In [ ]:
# Function to pull data for a specific network
networks = extract_dict.keys()
print(networks)

metrics = [metric_category]


messari.pull_network_data(networks, metrics, start_date, end_date, messari_api_key, messari_output_dir)

dict_keys(['ethereum', 'polygon-pos', 'internet-computer', 'polkadot', 'kusama', 'stellar', 'avalanche', 'celestia', 'binance-smart-chain', 'base', 'solana', 'optimism', 'cardano', 'tron', 'near', 'bitcoin', 'celo', 'arbitrum-one', 'starknet', 'algorand'])

Messari network data: 100%|██████████| 20/20 [00:05<00:00,  3.72pull/s]

All ecosystem data saved to data/raw/messari/ecosystem/

In [ ]:
# Test function to pull data for individual stablecoins
stablecoins = ['tether', 'circle-usdc-stablecoin']
metrics = ['supply']
messari.pull_stablecoin_data(stablecoins, metrics, start_date, end_date, messari_api_key, messari_output_dir)

Messari stablecoin data: 100%|██████████| 2/2 [00:02<00:00,  1.12s/pull]

All supply data saved to data/raw/messari/supply/

In [ ]:
# Test function to pull data for individual exchanges

exchanges = ['coinbase', 'gemini', 'kraken']
metrics = ['volume', 'futures-volume']
messari.pull_exchange_data(exchanges, metrics, start_date, end_date, messari_api_key, messari_output_dir)

Messari exchange data: 100%|██████████| 3/3 [00:03<00:00,  1.29s/pull]

All volume data saved to data/raw/messari/volume/
All futures-volume data saved to data/raw/messari/futures-volume/

In [ ]:
# COINGECKO
category = 'metadao-launchpad'  # https://www.coingecko.com/en/categories/metadao-launchpad
days = 365  # demo API tier max; daily granularity is automatic for days > 90

In [ ]:
# Pull daily USD price history for every token in a CoinGecko category.
# The token list is discovered dynamically from the category, so newly
# launched projects are picked up on each run.

assets = coingecko.get_category_coins(category, coingecko_api_key, coingecko_output_dir)
print(f'{len(assets)} tokens: {list(assets)}')
print()

coingecko.pull_asset_data(assets, coingecko_api_key, coingecko_output_dir, days=days)
print('Done')

12 tokens: ['solomon', 'p2p-protocol', 'umbra', 'rip-cars', 'avici', 'omnipair', 'laso-finance', 'loyal', 'jurassic-finance', 'paystream', 'zklsol', 'ranger']

CoinGecko price data: 100%|██████████| 12/12 [00:26<00:00,  2.24s/pull]

All price data saved to data/raw/coingecko/price/
Done

In [ ]:
# METADAO
# MetaDAO launchpad raises: ICO price from the on-chain launch accounts, first-week
# prices from MetaDAO's market API (no CoinGecko). Every participant in a MetaDAO sale
# pays the same price: the program mints a fixed 10M tokens to funders as a group, so
# ico_price_usd = usdc_accepted / 10,000,000. The steps below fill config/metadao_launches.json
# (hand-editable; the pull only adds what is missing) and build the hourly VWAP file
# that example-analysis.ipynb charts.
launch_config = 'config/metadao_launches.json'
n_days = 7              # first n days of trading to keep (hourly)
min_accepted_usd = 100_000   # new launches below this are written with include=false

In [ ]:
# Refresh: run this any time to check MetaDAO for new launches. Launches already on file are
# never repulled (a completed raise does not change). One fresh tickers call decides whether a
# new DAO launched since the last pull; only then are the launch accounts repulled and the new
# rows added to the config (existing rows untouched). Pairs and swaps are fetched only for
# launches that lack them or whose first n_days had not finished last time; the daily market
# data (tie-out only) is repulled only when new swaps came in; the processed hourly file is
# rebuilt only when an input changed. One line per step. Manual override to repull every
# launch account: metadao.pull_launches(metadao_output_dir, force=True).
metadao.refresh(launch_config, metadao_output_dir, metadao_processed_dir, n_days=n_days, min_accepted_usd=min_accepted_usd)

launch accounts: repulled v0.4 (6), v0.5 (7), v0.6 (41), v0.7 (153), v0.8 (0) in 2s
config: 69 launches, 16 included; no new launches
pairs: 14/16 included launches resolved; new: UMBRA, AVICI, LOYAL, ZKFG, PAYS, SOLO, RNGR, P2P, RAWR, LASO, CRED, CARS, ORDR, NECTAR; closed before the swap feed starts (2025-10-09), no price history: MTN, OMFG

MetaDAO launch swaps: 100%|██████████| 14/14 [02:15<00:00,  9.68s/pull]

swaps: 14 launches complete on file; pulled UMBRA (22,794 swaps), AVICI (22,445 swaps), LOYAL (7,215 swaps), ZKFG (7,090 swaps), PAYS (6,656 swaps), SOLO (17,443 swaps), RNGR (8,160 swaps), P2P (4,562 swaps), RAWR (6,884 swaps), LASO (2,509 swaps), CRED (17,998 swaps), CARS (3,684 swaps), ORDR (1,878 swaps), NECTAR (5,077 swaps); no pair: MTN, OMFG
[pull_market_data] failed: HTTP 400 HTTPError: 400 Client Error: Bad Request for url: https://market-api.metadao.fi/api/market-data?startDate=2025-10-01&endDate=2026-10-10
data/processed/metadao/launch-prices-7d.json: 14 launches x 168 hourly points; no swap history: MTN, OMFG; tie-out clean (ICO price identity on every launch; daily VWAP within 0.5% of MetaDAO on all 0 launch-days)

{'_metadata': {'n_days': 7,
  'freq': '1h',
  'price': 'hourly VWAP = USDC volume / token volume of every swap on the launch pair (MetaDAO spot AMM)',
  'multiple': 'vwap / ico_price_usd; ico_price_usd = usdc_accepted / 10,000,000 tokens',
  'built': '2026-10-10T14:11:53Z'},
 'launches': {'PRVT6TB7uss3FrUd2D9xs2zqDBsa3GbMJMwCQsgmeta': {'ticker': 'UMBRA',
   'name': 'Umbra',
   'ico_price_usd': 0.3,
   'usdc_accepted': 3000000.0,
   'usdc_committed': 154943746.0,
   'sale_closed': '2025-10-10',
   'trading_start': '2025-10-10T15:02:58Z',
   'pair_id': 'BLkBSE96kQys7SrMioKxeMiVbeo4Ckk2Y4n1JphKxYnv',
   'hours': [{'hour': 0,
     'ts': '2025-10-10T15:02:58Z',
     'vwap': 0.9813516648894771,
     'usdc_volume': 2156238.1975610005,
     'token_volume': 2197212.553569003,
     'trades': 1052,
     'multiple': 3.271172216298257},
    {'hour': 1,
     'ts': '2025-10-10T16:02:58Z',
     'vwap': 1.354299644356585,
     'usdc_volume': 1690822.0285939996,
     'token_volume': 1248484.436690001,
     'trades': 1193,
     'multiple': 4.514332147855283},
    {'hour': 2,
     'ts': '2025-10-10T17:02:58Z',
     'vwap': 1.2259019513469114,
     'usdc_volume': 971105.2366420003,
     'token_volume': 792155.7148800006,
     'trades': 1454,
     'multiple': 4.086339837823038},
    {'hour': 3,
     'ts': '2025-10-10T18:02:58Z',
     'vwap': 1.4211235343319781,
     'usdc_volume': 596378.211978,
     'token_volume': 419652.61820699996,
     'trades': 770,
     'multiple': 4.737078447773261},
    {'hour': 4,
     'ts': '2025-10-10T19:02:58Z',
     'vwap': 1.402337334082542,
     'usdc_volume': 498448.22958200076,
     'token_volume': 355441.0322450004,
     'trades': 745,
     'multiple': 4.67445778027514},
    {'hour': 5,
     'ts': '2025-10-10T20:02:58Z',
     'vwap': 1.2451472091478095,
     'usdc_volume': 509300.7122779995,
     'token_volume': 409028.51368599996,
     'trades': 506,
     'multiple': 4.150490697159365},
    {'hour': 6,
     'ts': '2025-10-10T21:02:58Z',
     'vwap': 0.8501923693290604,
     'usdc_volume': 973833.5874820008,
     'token_volume': 1145427.3439909997,
     'trades': 1503,
     'multiple': 2.8339745644302012},
    {'hour': 7,
     'ts': '2025-10-10T22:02:58Z',
     'vwap': 0.860183326390871,
     'usdc_volume': 256193.86190699998,
     'token_volume': 297836.3495860002,
     'trades': 333,
     'multiple': 2.8672777546362367},
    {'hour': 8,
     'ts': '2025-10-10T23:02:58Z',
     'vwap': 0.9749723742020433,
     'usdc_volume': 523048.59003699955,
     'token_volume': 536475.2929180005,
     'trades': 1356,
     'multiple': 3.249907914006811},
    {'hour': 9,
     'ts': '2025-10-11T00:02:58Z',
     'vwap': 1.091181656464181,
     'usdc_volume': 177736.07382900003,
     'token_volume': 162884.0374799999,
     'trades': 144,
     'multiple': 3.6372721882139367},
    {'hour': 10,
     'ts': '2025-10-11T01:02:58Z',
     'vwap': 0.943675530459106,
     'usdc_volume': 159979.467811,
     'token_volume': 169528.04501899998,
     'trades': 90,
     'multiple': 3.1455851015303535},
    {'hour': 11,
     'ts': '2025-10-11T02:02:58Z',
     'vwap': 0.9173113300667717,
     'usdc_volume': 195427.90896299997,
     'token_volume': 213044.25504999992,
     'trades': 138,
     'multiple': 3.0577044335559056},
    {'hour': 12,
     'ts': '2025-10-11T03:02:58Z',
     'vwap': 0.9983757914683755,
     'usdc_volume': 186397.10826800007,
     'token_volume': 186700.34856699986,
     'trades': 92,
     'multiple': 3.327919304894585},
    {'hour': 13,
     'ts': '2025-10-11T04:02:58Z',
     'vwap': 0.9062565322137103,
     'usdc_volume': 28818.607970999994,
     'token_volume': 31799.614068,
     'trades': 31,
     'multiple': 3.020855107379034},
    {'hour': 14,
     'ts': '2025-10-11T05:02:58Z',
     'vwap': 0.9284873024922926,
     'usdc_volume': 44663.00816799999,
     'token_volume': 48102.982182,
     'trades': 41,
     'multiple': 3.094957674974309},
    {'hour': 15,
     'ts': '2025-10-11T06:02:58Z',
     'vwap': 0.9731768303500241,
     'usdc_volume': 101821.65573200004,
     'token_volume': 104628.113367,
     'trades': 66,
     'multiple': 3.2439227678334137},
    {'hour': 16,
     'ts': '2025-10-11T07:02:58Z',
     'vwap': 1.1665836699654173,
     'usdc_volume': 383408.0818009999,
     'token_volume': 328658.87948900036,
     'trades': 253,
     'multiple': 3.888612233218058},
    {'hour': 17,
     'ts': '2025-10-11T08:02:58Z',
     'vwap': 1.3856442737365717,
     'usdc_volume': 385394.375974,
     'token_volume': 278133.7052220001,
     'trades': 229,
     'multiple': 4.618814245788573},
    {'hour': 18,
     'ts': '2025-10-11T09:02:58Z',
     'vwap': 1.5241199773854703,
     'usdc_volume': 472142.27609400015,
     'token_volume': 309780.25555700005,
     'trades': 297,
     'multiple': 5.080399924618234},
    {'hour': 19,
     'ts': '2025-10-11T10:02:58Z',
     'vwap': 1.5402857870571875,
     'usdc_volume': 458963.1828909999,
     'token_volume': 297972.744245,
     'trades': 247,
     'multiple': 5.134285956857292},
    {'hour': 20,
     'ts': '2025-10-11T11:02:58Z',
     'vwap': 1.5986564976238533,
     'usdc_volume': 316893.863072,
     'token_volume': 198225.1118629999,
     'trades': 167,
     'multiple': 5.328854992079512},
    {'hour': 21,
     'ts': '2025-10-11T12:02:58Z',
     'vwap': 1.4533356812266716,
     'usdc_volume': 104337.133338,
     'token_volume': 71791.489527,
     'trades': 74,
     'multiple': 4.844452270755572},
    {'hour': 22,
     'ts': '2025-10-11T13:02:58Z',
     'vwap': 1.478384690530893,
     'usdc_volume': 84002.764362,
     'token_volume': 56820.64005399997,
     'trades': 106,
     'multiple': 4.9279489684363105},
    {'hour': 23,
     'ts': '2025-10-11T14:02:58Z',
     'vwap': 1.6064074056871904,
     'usdc_volume': 228058.49039499986,
     'token_volume': 141968.02728100022,
     'trades': 256,
     'multiple': 5.354691352290635},
    {'hour': 24,
     'ts': '2025-10-11T15:02:58Z',
     'vwap': 1.5570657989266954,
     'usdc_volume': 169100.8260919999,
     'token_volume': 108602.23518400003,
     'trades': 160,
     'multiple': 5.190219329755651},
    {'hour': 25,
     'ts': '2025-10-11T16:02:58Z',
     'vwap': 1.4974747622548104,
     'usdc_volume': 109845.76515699994,
     'token_volume': 73354.00096599998,
     'trades': 89,
     'multiple': 4.991582540849368},
    {'hour': 26,
     'ts': '2025-10-11T17:02:58Z',
     'vwap': 1.4692874283899922,
     'usdc_volume': 115457.17500600002,
     'token_volume': 78580.38718300003,
     'trades': 58,
     'multiple': 4.897624761299974},
    {'hour': 27,
     'ts': '2025-10-11T18:02:58Z',
     'vwap': 1.4897220874954167,
     'usdc_volume': 73068.032366,
     'token_volume': 49048.096271999995,
     'trades': 98,
     'multiple': 4.9657402916513895},
    {'hour': 28,
     'ts': '2025-10-11T19:02:58Z',
     'vwap': 1.303034429774965,
     'usdc_volume': 233890.661404,
     'token_volume': 179496.91586000004,
     'trades': 143,
     'multiple': 4.343448099249883},
    {'hour': 29,
     'ts': '2025-10-11T20:02:58Z',
     'vwap': 1.1960932537213942,
     'usdc_volume': 115220.09971099993,
     'token_volume': 96330.36500499996,
     'trades': 104,
     'multiple': 3.9869775124046476},
    {'hour': 30,
     'ts': '2025-10-11T21:02:58Z',
     'vwap': 1.2032556391630758,
     'usdc_volume': 97413.61267100001,
     'token_volume': 80958.36786500002,
     'trades': 83,
     'multiple': 4.0108521305435865},
    {'hour': 31,
     'ts': '2025-10-11T22:02:58Z',
     'vwap': 1.310787368125272,
     'usdc_volume': 124501.19395499997,
     'token_volume': 94981.99096400003,
     'trades': 68,
     'multiple': 4.36929122708424},
    {'hour': 32,
     'ts': '2025-10-11T23:02:58Z',
     'vwap': 1.4574756828889346,
     'usdc_volume': 104551.89645799994,
     'token_volume': 71734.916531,
     'trades': 62,
     'multiple': 4.858252276296449},
    {'hour': 33,
     'ts': '2025-10-12T00:02:58Z',
     'vwap': 1.4937918188644714,
     'usdc_volume': 79893.99343700003,
     'token_volume': 53484.02128599999,
     'trades': 42,
     'multiple': 4.979306062881571},
    {'hour': 34,
     'ts': '2025-10-12T01:02:58Z',
     'vwap': 1.4391098354137715,
     'usdc_volume': 61077.52358400001,
     'token_volume': 42441.18279299999,
     'trades': 52,
     'multiple': 4.797032784712572},
    {'hour': 35,
     'ts': '2025-10-12T02:02:58Z',
     'vwap': 1.395530055555098,
     'usdc_volume': 106812.72803499998,
     'token_volume': 76539.18137400002,
     'trades': 51,
     'multiple': 4.651766851850327},
    {'hour': 36,
     'ts': '2025-10-12T03:02:58Z',
     'vwap': 1.4028443770743644,
     'usdc_volume': 89489.41513000002,
     'token_volume': 63791.40594099998,
     'trades': 59,
     'multiple': 4.6761479235812144},
    {'hour': 37,
     'ts': '2025-10-12T04:02:58Z',
     'vwap': 1.5857361059646533,
     'usdc_volume': 212176.09536900005,
     'token_volume': 133802.90363000004,
     'trades': 122,
     'multiple': 5.285787019882178},
    {'hour': 38,
     'ts': '2025-10-12T05:02:58Z',
     'vwap': 1.6790159647571057,
     'usdc_volume': 195904.64114700005,
     'token_volume': 116678.24800900005,
     'trades': 137,
     'multiple': 5.5967198825236855},
    {'hour': 39,
     'ts': '2025-10-12T06:02:58Z',
     'vwap': 1.8962445044204304,
     'usdc_volume': 348511.5827379996,
     'token_volume': 183790.424666,
     'trades': 235,
     'multiple': 6.320815014734768},
    {'hour': 40,
     'ts': '2025-10-12T07:02:58Z',
     'vwap': 1.9400684036573452,
     'usdc_volume': 366705.75287699985,
     'token_volume': 189016.91929300004,
     'trades': 220,
     'multiple': 6.466894678857818},
    {'hour': 41,
     'ts': '2025-10-12T08:02:58Z',
     'vwap': 1.8570610007341297,
     'usdc_volume': 293461.368076,
     'token_volume': 158024.62490999995,
     'trades': 161,
     'multiple': 6.190203335780432},
    {'hour': 42,
     'ts': '2025-10-12T09:02:58Z',
     'vwap': 1.7812415292986636,
     'usdc_volume': 93711.87837100004,
     'token_volume': 52610.42751899999,
     'trades': 91,
     'multiple': 5.937471764328879},
    {'hour': 43,
     'ts': '2025-10-12T10:02:58Z',
     'vwap': 1.8159448157835145,
     'usdc_volume': 82191.193518,
     'token_volume': 45260.84317299999,
     'trades': 70,
     'multiple': 6.053149385945049},
    {'hour': 44,
     'ts': '2025-10-12T11:02:58Z',
     'vwap': 1.7828085788512684,
     'usdc_volume': 21867.110480000003,
     'token_volume': 12265.540305,
     'trades': 21,
     'multiple': 5.942695262837562},
    {'hour': 45,
     'ts': '2025-10-12T12:02:58Z',
     'vwap': 1.642808026258501,
     'usdc_volume': 147542.94175500004,
     'token_volume': 89811.43225300002,
     'trades': 118,
     'multiple': 5.476026754195003},
    {'hour': 46,
     'ts': '2025-10-12T13:02:58Z',
     'vwap': 1.5780352532503061,
     'usdc_volume': 176282.631308,
     'token_volume': 111710.1984540001,
     'trades': 126,
     'multiple': 5.260117510834354},
    {'hour': 47,
     'ts': '2025-10-12T14:02:58Z',
     'vwap': 1.7702547877785393,
     'usdc_volume': 329492.97364299995,
     'token_volume': 186127.429745,
     'trades': 220,
     'multiple': 5.900849292595131},
    {'hour': 48,
     'ts': '2025-10-12T15:02:58Z',
     'vwap': 1.8712077650442194,
     'usdc_volume': 272609.2907019999,
     'token_volume': 145686.27588799995,
     'trades': 193,
     'multiple': 6.237359216814065},
    {'hour': 49,
     'ts': '2025-10-12T16:02:58Z',
     'vwap': 1.9467343096600387,
     'usdc_volume': 342783.82393699995,
     'token_volume': 176081.46229099997,
     'trades': 239,
     'multiple': 6.489114365533463},
    {'hour': 50,
     'ts': '2025-10-12T17:02:58Z',
     'vwap': 2.0848268314484426,
     'usdc_volume': 172796.99363799996,
     'token_volume': 82883.13975600002,
     'trades': 127,
     'multiple': 6.949422771494809},
    {'hour': 51,
     'ts': '2025-10-12T18:02:58Z',
     'vwap': 2.070458679896347,
     'usdc_volume': 198005.0467260001,
     'token_volume': 95633.42106200002,
     'trades': 145,
     'multiple': 6.901528932987824},
    {'hour': 52,
     'ts': '2025-10-12T19:02:58Z',
     'vwap': 2.1050038478450244,
     'usdc_volume': 162904.523755,
     'token_volume': 77389.180985,
     'trades': 88,
     'multiple': 7.016679492816748},
    {'hour': 53,
     'ts': '2025-10-12T20:02:58Z',
     'vwap': 2.223904446586084,
     'usdc_volume': 248523.73706400002,
     'token_volume': 111751.085999,
     'trades': 194,
     'multiple': 7.413014821953614},
    {'hour': 54,
     'ts': '2025-10-12T21:02:58Z',
     'vwap': 2.3726357063655312,
     'usdc_volume': 324099.97338899993,
     'token_volume': 136599.13003900004,
     'trades': 209,
     'multiple': 7.908785687885104},
    {'hour': 55,
     'ts': '2025-10-12T22:02:58Z',
     'vwap': 2.251157129369319,
     'usdc_volume': 188598.52599299993,
     'token_volume': 83778.48153399999,
     'trades': 94,
     'multiple': 7.50385709789773},
    {'hour': 56,
     'ts': '2025-10-12T23:02:58Z',
     'vwap': 2.156646484945548,
     'usdc_volume': 160035.40655799996,
     'token_volume': 74205.674261,
     'trades': 87,
     'multiple': 7.188821616485161},
    {'hour': 57,
     'ts': '2025-10-13T00:02:58Z',
     'vwap': 2.2193170854957454,
     'usdc_volume': 85193.10943499996,
     'token_volume': 38387.083122000004,
     'trades': 42,
     'multiple': 7.3977236183191515},
    {'hour': 58,
     'ts': '2025-10-13T01:02:58Z',
     'vwap': 2.099031045993707,
     'usdc_volume': 99845.008757,
     'token_volume': 47567.190083999994,
     'trades': 51,
     'multiple': 6.996770153312357},
    {'hour': 59,
     'ts': '2025-10-13T02:02:58Z',
     'vwap': 2.1928326460946503,
     'usdc_volume': 71787.916491,
     'token_volume': 32737.52633099999,
     'trades': 46,
     'multiple': 7.309442153648835},
    {'hour': 60,
     'ts': '2025-10-13T03:02:58Z',
     'vwap': 2.087234284151924,
     'usdc_volume': 149417.28996799997,
     'token_volume': 71586.25703999998,
     'trades': 82,
     'multiple': 6.957447613839746},
    {'hour': 61,
     'ts': '2025-10-13T04:02:58Z',
     'vwap': 2.0637937401210724,
     'usdc_volume': 87383.76428399998,
     'token_volume': 42341.326357000005,
     'trades': 46,
     'multiple': 6.879312467070242},
    {'hour': 62,
     'ts': '2025-10-13T05:02:58Z',
     'vwap': 2.1533082722838466,
     'usdc_volume': 137183.63583500002,
     'token_volume': 63708.312275,
     'trades': 71,
     'multiple': 7.177694240946155},
    {'hour': 63,
     'ts': '2025-10-13T06:02:58Z',
     'vwap': 2.2751838385652543,
     'usdc_volume': 113008.58873100003,
     'token_volume': 49670.091187999984,
     'trades': 74,
     'multiple': 7.583946128550848},
    {'hour': 64,
     'ts': '2025-10-13T07:02:58Z',
     'vwap': 2.435406192268653,
     'usdc_volume': 185402.346091,
     'token_volume': 76127.894673,
     'trades': 97,
     'multiple': 8.11802064089551},
    {'hour': 65,
     'ts': '2025-10-13T08:02:58Z',
     'vwap': 2.3602898595245616,
     'usdc_volume': 120135.61069900008,
     'token_volume': 50898.66832000001,
     'trades': 90,
     'multiple': 7.867632865081872},
    {'hour': 66,
     'ts': '2025-10-13T09:02:58Z',
     'vwap': 2.211448660678289,
     'usdc_volume': 172232.16119400001,
     'token_volume': 77882.052727,
     'trades': 108,
     'multiple': 7.371495535594296},
    {'hour': 67,
     'ts': '2025-10-13T10:02:58Z',
     'vwap': 2.0141755367349803,
     'usdc_volume': 206482.36762599996,
     'token_volume': 102514.58418600004,
     'trades': 102,
     'multiple': 6.713918455783268},
    {'hour': 68,
     'ts': '2025-10-13T11:02:58Z',
     'vwap': 1.869539803599423,
     'usdc_volume': 239948.05078299993,
     'token_volume': 128346.05089500004,
     'trades': 158,
     'multiple': 6.23179934533141},
    {'hour': 69,
     'ts': '2025-10-13T12:02:58Z',
     'vwap': 1.925438807630667,
     'usdc_volume': 182524.228684,
     'token_volume': 94796.17215599996,
     'trades': 133,
     'multiple': 6.418129358768891},
    {'hour': 70,
     'ts': '2025-10-13T13:02:58Z',
     'vwap': 1.8539165258881067,
     'usdc_volume': 191756.479356,
     'token_volume': 103433.17872100002,
     'trades': 126,
     'multiple': 6.179721752960356},
    {'hour': 71,
     'ts': '2025-10-13T14:02:58Z',
     'vwap': 1.8208816254432456,
     'usdc_volume': 272355.32445499994,
     'token_volume': 149573.32791400002,
     'trades': 132,
     'multiple': 6.069605418144152},
    {'hour': 72,
     'ts': '2025-10-13T15:02:58Z',
     'vwap': 1.6725546011214716,
     'usdc_volume': 290117.0757070001,
     'token_volume': 173457.46172499988,
     'trades': 191,
     'multiple': 5.575182003738239},
    {'hour': 73,
     'ts': '2025-10-13T16:02:58Z',
     'vwap': 1.6957396763892518,
     'usdc_volume': 155778.11051200007,
     'token_volume': 91864.40152400002,
     'trades': 103,
     'multiple': 5.652465587964173},
    {'hour': 74,
     'ts': '2025-10-13T17:02:58Z',
     'vwap': 1.6495097858547147,
     'usdc_volume': 248515.933304,
     'token_volume': 150660.47830400005,
     'trades': 147,
     'multiple': 5.498365952849049},
    {'hour': 75,
     'ts': '2025-10-13T18:02:58Z',
     'vwap': 1.684539094168931,
     'usdc_volume': 81266.58868199999,
     'token_volume': 48242.625513,
     'trades': 66,
     'multiple': 5.6151303138964375},
    {'hour': 76,
     'ts': '2025-10-13T19:02:58Z',
     'vwap': 1.7228220368330458,
     'usdc_volume': 23481.105726999995,
     'token_volume': 13629.443567,
     'trades': 23,
     'multiple': 5.742740122776819},
    {'hour': 77,
     'ts': '2025-10-13T20:02:58Z',
     'vwap': 1.7788982838683824,
     'usdc_volume': 42338.493462000006,
     'token_volume': 23800.401544000004,
     'trades': 44,
     'multiple': 5.9296609462279415},
    {'hour': 78,
     'ts': '2025-10-13T21:02:58Z',
     'vwap': 1.6538598492127707,
     'usdc_volume': 215245.37222999998,
     'token_volume': 130147.28686499991,
     'trades': 139,
     'multiple': 5.51286616404257},
    {'hour': 79,
     'ts': '2025-10-13T22:02:58Z',
     'vwap': 1.4630895778541542,
     'usdc_volume': 284797.97636399994,
     'token_volume': 194655.18767599997,
     'trades': 210,
     'multiple': 4.876965259513847},
    {'hour': 80,
     'ts': '2025-10-13T23:02:58Z',
     'vwap': 1.530277158659975,
     'usdc_volume': 36796.90035299999,
     'token_volume': 24045.905766,
     'trades': 39,
     'multiple': 5.100923862199917},
    {'hour': 81,
     'ts': '2025-10-14T00:02:58Z',
     'vwap': 1.4667636291444233,
     'usdc_volume': 79531.03596499997,
     'token_volume': 54222.121673,
     'trades': 85,
     'multiple': 4.889212097148078},
    {'hour': 82,
     'ts': '2025-10-14T01:02:58Z',
     'vwap': 1.4479978762838548,
     'usdc_volume': 61941.535929,
     'token_volume': 42777.366558,
     'trades': 47,
     'multiple': 4.826659587612849},
    {'hour': 83,
     'ts': '2025-10-14T02:02:58Z',
     'vwap': 1.387496168256484,
     'usdc_volume': 81064.69359400001,
     'token_volume': 58425.165740000004,
     'trades': 70,
     'multiple': 4.624987227521613},
    {'hour': 84,
     'ts': '2025-10-14T03:02:58Z',
     'vwap': 1.4562815593066687,
     'usdc_volume': 114109.50118799998,
     'token_volume': 78356.75763300002,
     'trades': 62,
     'multiple': 4.854271864355563},
    {'hour': 85,
     'ts': '2025-10-14T04:02:58Z',
     'vwap': 1.4180744547130215,
     'usdc_volume': 117962.106773,
     'token_volume': 83184.706121,
     'trades': 73,
     'multiple': 4.726914849043405},
    {'hour': 86,
     'ts': '2025-10-14T05:02:58Z',
     'vwap': 1.3144595875292016,
     'usdc_volume': 170546.198344,
     'token_volume': 129746.247022,
     'trades': 116,
     'multiple': 4.3815319584306724},
    {'hour': 87,
     'ts': '2025-10-14T06:02:58Z',
     'vwap': 1.2062040506551175,
     'usdc_volume': 239034.19845300002,
     'token_volume': 198170.61493299992,
     'trades': 160,
     'multiple': 4.020680168850392},
    {'hour': 88,
     'ts': '2025-10-14T07:02:58Z',
     'vwap': 1.2553872136597914,

In [ ]:
# The individual steps refresh() runs, for debugging or partial reruns.
# 1. Launch accounts -> config. getProgramAccounts on each launchpad program (v0.4-v0.8), saved
# as returned under launches/ (existing files are kept; force=True repulls all, a few seconds),
# decoded, and added to the config where missing.
metadao.pull_launches(metadao_output_dir)
decoded = metadao.decode_launches(metadao_output_dir)
metadao.fill_launch_config(launch_config, decoded, metadao_output_dir, min_accepted_usd=min_accepted_usd)

launch accounts: 5 program file(s) fresh (oldest 3m ago), kept
decoded 206 launch accounts; 1 skipped as undecodable: v0.4 7uDTCorL... (v0.4 layout leaves 71 non-zero trailing bytes)
config: 69 launches, 16 included; no new launches

{'_metadata': {'description': 'MetaDAO launchpad raises. Hand-editable: metadao.fill_launch_config only adds missing launches and missing keys, it never overwrites a value. Set include=false to drop a launch from the charts without deleting it.',
  'price_formula': 'ico_price_usd = usdc_accepted / tokens_to_participants (the program mints a fixed 10,000,000 tokens to funders as a group, pro rata to accepted USDC)',
  'usdc_accepted': 'total_approved_amount (v0.7+), final_raise_amount (v0.6) or committed (v0.4/v0.5) from the on-chain Launch account, in USDC',
  'programs': {'v0.4': 'AfJJJ5UqxhBKoE3grkKAZZsoXDE9kncbMKvqSHGsCNrE',
   'v0.5': 'mooNhciQJi1LqHDmse2JPic2NqG2PXCanbE3ZYzP3qA',
   'v0.6': 'MooNyh4CBUYEKyXVnjGYQ8mEiJDpGvJMdvrZx1iGeHV',
   'v0.7': 'moontUzsdepotRGe5xsfip7vLPTJnVuafqdUWexVnPM',
   'v0.8': 'moonDJUoHteKkGATejA5bdJVwJ6V6Dg74gyqyJTx73n'},
  'launch_discriminator_base64': 'kDMzo85V1SY='},
 'launches': {'9BEzsxayF8rx4AEsN9duFBn3NQDUf1hX3eTWPJQmeta': {'ticker': 'KOL',
   'name': 'Kollan',
   'launchpad_version': 'v0.4',
   'launch_account': 'AoPCn9kLv64hiK9gaJjgAEsXg1eeE4aPwPTHbMAUJti8',
   'sale_started': '2025-04-02',
   'sale_closed': '2025-04-02',
   'sale_completed': None,
   'usdc_committed': 6.0,
   'usdc_accepted': 6.0,
   'tokens_to_participants': 10000000,
   'ico_price_usd': 6e-07,
   'pair_id': None,
   'include': False,
   'source': 'on-chain Launch account (metadao.pull_launches)',
   'notes': None},
  'mtnc7NNSpAJuvYNmayXU63WhWZGgFzwQ2yeYWqemeta': {'ticker': 'MTN',
   'name': 'mtnCapital',
   'launchpad_version': 'v0.4',
   'launch_account': 'a3wqnp5LSi84ShMFwfPgULA3rVaNcL67UwTyccbMDNo',
   'sale_started': '2025-04-02',
   'sale_closed': '2025-04-09',
   'sale_completed': None,
   'usdc_committed': 5758964.0,
   'usdc_accepted': 5758964.0,
   'tokens_to_participants': 10000000,
   'ico_price_usd': 0.5758964,
   'pair_id': None,
   'include': True,
   'source': 'on-chain Launch account (metadao.pull_launches)',
   'notes': None},
  'ey9DmQUxPKnABU6LrWsQCvFVhZcYk2j4BmBSXLKmeta': {'ticker': 'RSTFUL',
   'name': 'Rustfully',
   'launchpad_version': 'v0.5',
   'launch_account': '7yb2q6kxKGVmzyCnnK3EYHpApwvZmghf3Kv34aayDRwb',
   'sale_started': '2025-07-18',
   'sale_closed': '2025-07-18',
   'sale_completed': None,
   'usdc_committed': 31.0,
   'usdc_accepted': 31.0,
   'tokens_to_participants': 10000000,
   'ico_price_usd': 3.1e-06,
   'pair_id': None,
   'include': False,
   'source': 'on-chain Launch account (metadao.pull_launches)',
   'notes': None},
  'WnbW7kcpfKzrDhujtTD8MFfqc8mck4o26fbTRSameta': {'ticker': 'PFT',
   'name': 'PFT',
   'launchpad_version': 'v0.5',
   'launch_account': '7DzBXBYSKhrXHPWT6mAKq394vKupaKaqLn9bK1wscpBz',
   'sale_started': '2025-07-20',
   'sale_closed': '2025-07-20',
   'sale_completed': None,
   'usdc_committed': 10.0,
   'usdc_accepted': 10.0,
   'tokens_to_participants': 10000000,
   'ico_price_usd': 1e-06,
   'pair_id': None,
   'include': False,
   'source': 'on-chain Launch account (metadao.pull_launches)',
   'notes': None},
  'omfgRBnxHsNJh6YeGbGAmWenNkenzsXyBXm3WDhmeta': {'ticker': 'OMFG',
   'name': 'Omnipair',
   'launchpad_version': 'v0.5',
   'launch_account': 'DHW6DToYjhwknzVCDvZ6r7hSv7ZpGw9adEN8NvZuUpVh',
   'sale_started': '2025-07-21',
   'sale_closed': '2025-07-28',
   'sale_completed': None,
   'usdc_committed': 1118102.0,
   'usdc_accepted': 1118102.0,
   'tokens_to_participants': 10000000,
   'ico_price_usd': 0.1118102,
   'pair_id': None,
   'include': True,
   'source': 'on-chain Launch account (metadao.pull_launches)',
   'notes': None},
  '8XaEjbnWERh9qwgEwM4BGmn4C95cmVoHtuy81A9ghD6D': {'ticker': 'EXMPL',
   'name': 'Example',
   'launchpad_version': 'v0.6',
   'launch_account': 'DnA962s6F6FF2vuJJMEbRTibVRhfkCm1Rj9Gfcsm41vc',
   'sale_started': '2025-09-29',
   'sale_closed': '2025-09-29',
   'sale_completed': None,
   'usdc_committed': 0.5,
   'usdc_accepted': 0.5,
   'tokens_to_participants': 10000000,
   'ico_price_usd': 5e-08,
   'pair_id': None,
   'include': False,
   'source': 'on-chain Launch account (metadao.pull_launches)',
   'notes': None},
  '2yei47BYXeGuvabpSFXjmfhg6gJ2J9T2xAWHZjwtX5uX': {'ticker': 'CRIME',
   'name': 'Crimera',
   'launchpad_version': 'v0.6',
   'launch_account': 'FYg9XBPBTcxJeNckDx6T19WCQ5tWdjpww5EPFoSoRm5R',
   'sale_started': '2025-09-30',
   'sale_closed': '2025-09-30',
   'sale_completed': None,
   'usdc_committed': 12.0,
   'usdc_accepted': 12.0,
   'tokens_to_participants': 10000000,
   'ico_price_usd': 1.2e-06,
   'pair_id': None,
   'include': False,
   'source': 'on-chain Launch account (metadao.pull_launches)',
   'notes': None},
  'Fsce3kKc7QLdQ1Lr9ahVPDRVYdRW4WdjcnsBeBXe2uHC': {'ticker': 'CRIME',
   'name': 'Crimera',
   'launchpad_version': 'v0.6',
   'launch_account': '7BWfg6HHTa1D77wztFX9SVsgXAGdFpQYV8y398JKfWUR',
   'sale_started': '2025-09-30',
   'sale_closed': '2025-09-30',
   'sale_completed': None,
   'usdc_committed': 11.0,
   'usdc_accepted': 11.0,
   'tokens_to_participants': 10000000,
   'ico_price_usd': 1.1e-06,
   'pair_id': None,
   'include': False,
   'source': 'on-chain Launch account (metadao.pull_launches)',
   'notes': None},
  '4Ueb677S8FVCH5ot5rrB6MFq5XsFgpQBgri1oNCnx6HW': {'ticker': 'PPRD',
   'name': 'PreProd',
   'launchpad_version': 'v0.6',
   'launch_account': 'GMjjUC8Z6qjVRX9CXgYz6BNrYcnzUyKpgkkmcsbCCUix',
   'sale_started': '2025-10-04',
   'sale_closed': '2025-10-04',
   'sale_completed': None,
   'usdc_committed': 10000.0,
   'usdc_accepted': 10000.0,
   'tokens_to_participants': 10000000,
   'ico_price_usd': 0.001,
   'pair_id': None,
   'include': False,
   'source': 'on-chain Launch account (metadao.pull_launches)',
   'notes': None},
  '4aLjJawZZ7rHb1aLmGq6KnNqf39mW7Qsu1vuRTvTCqiH': {'ticker': 'FTD',
   'name': 'FTD',
   'launchpad_version': 'v0.6',
   'launch_account': 'YsrWGAXyZcx1Q4CGSRAiuZXsYGNjfbwkcu1JirTMsVi',
   'sale_started': '2025-10-04',
   'sale_closed': '2025-10-05',
   'sale_completed': None,
   'usdc_committed': 27.0,
   'usdc_accepted': 27.0,
   'tokens_to_participants': 10000000,
   'ico_price_usd': 2.7e-06,
   'pair_id': None,
   'include': False,
   'source': 'on-chain Launch account (metadao.pull_launches)',
   'notes': None},
  'PRVT6TB7uss3FrUd2D9xs2zqDBsa3GbMJMwCQsgmeta': {'ticker': 'UMBRA',
   'name': 'Umbra',
   'launchpad_version': 'v0.6',
   'launch_account': '9kx7UDFzFt7e2V4pFtawnupKKvRR3EhV7P1Pxmc5XCQj',
   'sale_started': '2025-10-06',
   'sale_closed': '2025-10-10',
   'sale_completed': None,
   'usdc_committed': 154943746.0,
   'usdc_accepted': 3000000.0,
   'tokens_to_participants': 10000000,
   'ico_price_usd': 0.3,
   'pair_id': 'BLkBSE96kQys7SrMioKxeMiVbeo4Ckk2Y4n1JphKxYnv',
   'include': True,
   'source': 'on-chain Launch account (metadao.pull_launches)',
   'notes': None},
  '4qeRy1oBAkpTVoLWYkRCaearcYFvpvramGQLkLmfZcDd': {'ticker': 'TSTAVI',
   'name': 'TSTAVI',
   'launchpad_version': 'v0.6',
   'launch_account': 'GALBgKek7GRcqddP388jEjKPQ1CM9ghL8U5ev7qipZm',
   'sale_started': '2025-10-14',
   'sale_closed': '2025-10-14',
   'sale_completed': None,
   'usdc_committed': 36.0,
   'usdc_accepted': 21.0,
   'tokens_to_participants': 10000000,
   'ico_price_usd': 2.1e-06,
   'pair_id': None,
   'include': False,
   'source': 'on-chain Launch account (metadao.pull_launches)',
   'notes': None},
  '7AQbeEfCeFUNAvQvqHfhB6gJgM7srN8YzfHWu2YN2eyE': {'ticker': 'TEST',
   'name': 'Test',
   'launchpad_version': 'v0.6',
   'launch_account': '25f25n7HTBcBisbmAcNMsrwtMy4MyJKMeW67ifAQPhjU',
   'sale_started': '2025-10-14',
   'sale_closed': '2025-10-14',
   'sale_completed': None,
   'usdc_committed': 13.0,
   'usdc_accepted': 10.0,
   'tokens_to_participants': 10000000,
   'ico_price_usd': 1e-06,
   'pair_id': None,
   'include': False,
   'source': 'on-chain Launch account (metadao.pull_launches)',
   'notes': None},
  'ATZKEKSNqvauS2YdoeQhEBZDvF35JLohboA1mDr3GMEn': {'ticker': 'TEST',
   'name': 'Test',
   'launchpad_version': 'v0.6',
   'launch_account': 'GcqnStMCiSJyt82dSDAV3kmHH2eNKhPvseCEFD3bFL5E',
   'sale_started': '2025-10-14',
   'sale_closed': '2025-10-14',
   'sale_completed': None,
   'usdc_committed': 12.0,
   'usdc_accepted': 11.0,
   'tokens_to_participants': 10000000,
   'ico_price_usd': 1.1e-06,
   'pair_id': None,
   'include': False,
   'source': 'on-chain Launch account (metadao.pull_launches)',
   'notes': None},
  'C5yXcUj9stvaW6cPTmmxWyCCjLxxCiJtYnwKGS129vGJ': {'ticker': 'TEST',
   'name': 'Test',
   'launchpad_version': 'v0.6',
   'launch_account': '7PYiTqb91zrDMuuR2KbXNyVBZTP14FVge41zE8CSY7Ci',
   'sale_started': '2025-10-14',
   'sale_closed': '2025-10-14',
   'sale_completed': None,
   'usdc_committed': 11.0,
   'usdc_accepted': 11.0,
   'tokens_to_participants': 10000000,
   'ico_price_usd': 1.1e-06,
   'pair_id': None,
   'include': False,
   'source': 'on-chain Launch account (metadao.pull_launches)',
   'notes': None},
  'GqC4nrFEKWA3w7Skavxt5zyEzWi6WE5CceSVhqzNsQjR': {'ticker': 'TEST',
   'name': 'Test',
   'launchpad_version': 'v0.6',
   'launch_account': 'FQU7ywu6w1n9bTx16PbTqk562Jy1ctERxxkRHRzGrKeJ',
   'sale_started': '2025-10-14',
   'sale_closed': '2025-10-14',
   'sale_completed': None,
   'usdc_committed': 13.0,
   'usdc_accepted': 13.0,
   'tokens_to_participants': 10000000,
   'ico_price_usd': 1.3e-06,
   'pair_id': None,
   'include': False,
   'source': 'on-chain Launch account (metadao.pull_launches)',
   'notes': None},
  '7X6DYSHEJEFMEhJcL9t8YFv7YcJwKqNWwi3NAdJ3EDud': {'ticker': 'TST30M',
   'name': 'Test30',
   'launchpad_version': 'v0.6',
   'launch_account': '7wpnUjdt6kwVYKhnkSDpMT45UKhUcRZibQETZLVriry8',
   'sale_started': '2025-10-17',
   'sale_closed': '2025-10-17',
   'sale_completed': None,
   'usdc_committed': 15.0,
   'usdc_accepted': 15.0,
   'tokens_to_participants': 10000000,
   'ico_price_usd': 1.5e-06,
   'pair_id': None,
   'include': False,
   'source': 'on-chain Launch account (metadao.pull_launches)',
   'notes': None},
  'EjvxFhuzMoFiXuuKU82Dfv1xw5VWReoPS1ErkZ2xvQDL': {'ticker': 'TST30',
   'name': 'Test half hour',
   'launchpad_version': 'v0.6',
   'launch_account': '3nuUSZ8tpSwqqLqDtAd81mrTF6gKanFxqwZBDrXENpEH',
   'sale_started': '2025-10-17',
   'sale_closed': '2025-10-17',
   'sale_completed': None,
   'usdc_committed': 17.0,
   'usdc_accepted': 10.0,
   'tokens_to_participants': 10000000,
   'ico_price_usd': 1e-06,
   'pair_id': None,
   'include': False,
   'source': 'on-chain Launch account (metadao.pull_launches)',
   'notes': None},
  'BANKJmvhT8tiJRsBSS1n2HryMBPvT5Ze4HU95DUAmeta': {'ticker': 'AVICI',
   'name': 'Avici',
   'launchpad_version': 'v0.6',
   'launch_account': '2rYvdtK8ovuSziJuy5gTTPtviY5CfTnW6Pps4pk7ehEq',
   'sale_started': '2025-10-14',
   'sale_closed': '2025-10-18',
   'sale_completed': None,
   'usdc_committed': 34230976.0,
   'usdc_accepted': 3500000.0,
   'tokens_to_participants': 10000000,
   'ico_price_usd': 0.35,
   'pair_id': '3D854kknnQhu9xVaRNV154oZ9oN2WF3tXsq3LDu7fFMn',
   'include': True,
   'source': 'on-chain Launch account (metadao.pull_launches)',
   'notes': None},
  'F1vYk6VERRasDhW1fq7aru3sTDNMH9q5d62RZvNypE7T': {'ticker': 'TSTJUP',
   'name': 'TestJUP',
   'launchpad_version': 'v0.6',
   'launch_account': 'FViootVxjTR7hPmqQLSiRUMvyAVWs3ptqwrm1HNT1VZR',
   'sale_started': '2025-10-18',
   'sale_closed': '2025-10-18',
   'sale_completed': None,
   'usdc_committed': 20.0,
   'usdc_accepted': 20.0,
   'tokens_to_participants': 10000000,
   'ico_price_usd': 2e-06,
   'pair_id': None,
   'include': False,
   'source': 'on-chain Launch account (metadao.pull_launches)',
   'notes': None},
  'LYLikzBQtpa9ZgVrJsqYGQpR3cC1WMJrBHaXGrQmeta': {'ticker': 'LOYAL',
   'name': 'Loyal',
   'launchpad_version': 'v0.6',
   'launch_account': 'E7kXdSdZrjVFDkLb6V7S8VihKookPviRJ7tXVik9qbdu',
   'sale_started': '2025-10-18',
   'sale_closed': '2025-10-22',
   'sale_completed': None,
   'usdc_committed': 75898233.0,
   'usdc_accepted': 2500000.0,
   'tokens_to_participants': 10000000,
   'ico_price_usd': 0.25,
   'pair_id': 'GxpJkPEsPmuRCCTNnfZaDKg4X3gf4ZPgmqgFqtibaPtK',
   'include': True,
   'source': 'on-chain Launch account (metadao.pull_launches)',
   'notes': None},
  'ZKFHiLAfAFMTcDAuCtjNW54VzpERvoe7PBF9mYgmeta': {'ticker': 'ZKFG',
   'name': 'ZKFG',
   'launchpad_version': 'v0.6',
   'launch_account': '4h248CdXdeWtxWnHxEPqa5ruYZaEwXRZPyDFYnndbzpR',
   'sale_started': '2025-10-20',
   'sale_closed': '2025-10-24',
   'sale_completed': None,
   'usdc_committed': 14886359.0,
   'usdc_accepted': 969420.0,
   'tokens_to_participants': 10000000,
   'ico_price_usd': 0.096942,
   'pair_id': '5FPGRzY9ArJFwY2Hp2y2eqMzVewyWCBox7esmpuZfCvE',
   'include': True,
   'source': 'on-chain Launch account (metadao.pull_launches)',
   'notes': None},
  'PAYZP1W3UmdEsNLJwmH61TNqACYJTvhXy8SCN4Tmeta': {'ticker': 'PAYS',
   'name': 'Paystream',
   'launchpad_version': 'v0.6',
   'launch_account': '13YpYe4k5GPaD2vZvvY7v7if31S1Wu8yWShkQs8MzLNh',
   'sale_started': '2025-10-23',
   'sale_closed': '2025-10-27',
   'sale_completed': None,
   'usdc_committed': 6149247.0,
   'usdc_accepted': 750000.0,
   'tokens_to_participants': 10000000,
   'ico_price_usd': 0.075,
   'pair_id': '6FRXzTe3HajL8Fwmmkupp8g3y3wn3g3QEjj8sABndre3',
   'include': True,
   'source': 'on-chain Launch account (metadao.pull_launches)',
   'notes': None},
  '4ZYGY49yFDjJVgmSxRypXHvPhPi5vNfxbBCTDapyNdAR': {'ticker': 'EXMPL',
   'name': 'Example Token',
   'launchpad_version': 'v0.6',
   'launch_account': '48UeghTJDcUugF4hsSECLrotWY2pxSTuA9b87R8zybQn',
   'sale_started': '2025-11-18',
   'sale_closed': '2025-11-18',
   'sale_completed': None,
   'usdc_committed': 22.0,
   'usdc_accepted': 15.0,
   'tokens_to_participants': 10000000,
   'ico_price_usd': 1.5e-06,
   'pair_id': None,
   'include': False,
   'source': 'on-chain Launch account (metadao.pull_launches)',
   'notes': None},
  'SoLo9oxzLDpcq1dpqAgMwgce5WqkRDtNXK7EPnbmeta': {'ticker': 'SOLO',
   'name': 'Solomon',
   'launchpad_version': 'v0.6',
   'launch_account': '634r63NH2qbTrSVyLieC3Ab3YKaEfoGnCLM8idZMEycE',
   'sale_started': '2025-11-14',
   'sale_closed': '2025-11-18',
   'sale_completed': None,
   'usdc_committed': 102932673.08,
   'usdc_accepted': 8000000.0,
   'tokens_to_participants': 10000000,
   'ico_price_usd': 0.8,
   'pair_id': 'DzYtzoNvPbyFCzwZA6cSm9eDEEmxEB9f8AGkJXUXgnSA',
   'include': True,
   'source': 'on-chain Launch account (metadao.pull_launches)',
   'notes': None},
  '5tmUS4qhr7aJpgfxKtZucjfqwwSWBNomUN9GDExv6pko': {'ticker': 'EXMPL',
   'name': 'Example Token',
   'launchpad_version': 'v0.6',
   'launch_account': '2nR9DTVFtmzpEaf9HMsjJW3qc9hwsUmsb4rFbmTbyZ33',
   'sale_started': '2025-12-02',
   'sale_closed': '2025-12-03',
   'sale_completed': None,
   'usdc_committed': 11.0,
   'usdc_accepted': 11.0,
   'tokens_to_participants': 10000000,
   'ico_price_usd': 1.1e-06,
   'pair_id': None,
   'include': False,
   'source': 'on-chain Launch account (metadao.pull_launches)',
   'notes': None},
  '7EJRXkBfoAYtzAXE7PRry4gqh6NciY3Yt5YF3GR8LC8V': {'ticker': 'TEST',
   'name': 'Test Token',
   'launchpad_version': 'v0.7',
   'launch_account': 'GFbxeJoiPMdPuhdZQqNxxFqYWpi3RWiXfYwDTGhiAfQz',
   'sale_started': '2025-12-26',
   'sale_closed': '2025-12-26',
   'sale_completed': '2025-12-26',
   'usdc_committed': 7.0,
   'usdc_accepted': 7.0,
   'tokens_to_participants': 10000000,
   'ico_price_usd': 7e-07,
   'pair_id': None,
   'include': False,
   'source': 'on-chain Launch account (metadao.pull_launches)',
   'notes': None},
  '9m2xaDCUwGA1r3GTWNwEA1oAmeHx53QUGBxsnYAK7bUG': {'ticker': 'TEST',
   'name': 'Test',
   'launchpad_version': 'v0.7',
   'launch_account': 'FvQCwxmELEr7Dis8eQsij1F53wxgMohSiEZ9jMLMCapm',
   'sale_started': '2025-12-30',
   'sale_closed': '2025-12-30',
   'sale_completed': '2025-12-30',
   'usdc_committed': 20.0,
   'usdc_accepted': 10.0,
   'tokens_to_participants': 10000000,
   'ico_price_usd': 1e-06,
   'pair_id': None,
   'include': False,
   'source': 'on-chain Launch account (metadao.pull_launches)',
   'notes': None},
  'GCU4rpSTk2JavuTvYJGP6ah7RxEo5xaKrsRRfLwNkH45': {'ticker': 'TEST',
   'name': 'Test',
   'launchpad_version': 'v0.7',
   'launch_account': 'HUM66D4uRnWTFHm3fJkA2rvQWqpHnJZWgRUt5QNxWF6E',
   'sale_started': '2026-01-03',
   'sale_closed': '2026-01-03',
   'sale_completed': '2026-01-03',
   'usdc_committed': 20.0,
   'usdc_accepted': 20.0,
   'tokens_to_participants': 10000000,
   'ico_price_usd': 2e-06,
   'pair_id': None,
   'include': False,
   'source': 'on-chain Launch account (metadao.pull_launches)',
   'notes': None},
  '4gjaKkjA9UANid6cyYH4p4asVUnhJdLRB5mgdPE67beo': {'ticker': 'TST',
   'name': 'Test',
   'launchpad_version': 'v0.7',
   'launch_account': 'XvSQC1LzLfdjkCceT2QTkstNFpNfLfFGiJeyMxtXZxo',
   'sale_started': '2026-01-06',
   'sale_closed': '2026-01-06',
   'sale_completed': '2026-01-06',
   'usdc_committed': 7.0,
   'usdc_accepted': 6.0,
   'tokens_to_participants': 10000000,
   'ico_price_usd': 6e-07,
   'pair_id': None,
   'include': False,
   'source': 'on-chain Launch account (metadao.pull_launches)',
   'notes': None},
  '7vmUFwmADQHBNB8LwpSAExxdMsxfUU3Kc7N8ZDPkbixi': {'ticker': 'MTKN',
   'name': 'MyToken',
   'launchpad_version': 'v0.7',
   'launch_account': 'BKguq2VeUqKN1JTDdLzda4K44Sj83avfHgGoE5CYovGU',
   'sale_started': '2026-01-06',
   'sale_closed': '2026-01-06',
   'sale_completed': '2026-01-06',
   'usdc_committed': 2.0,
   'usdc_accepted': 2.0,
   'tokens_to_participants': 10000000,
   'ico_price_usd': 2e-07,
   'pair_id': None,
   'include': False,
   'source': 'on-chain Launch account (metadao.pull_launches)',
   'notes': None},
  'FEPBkwPxvPUvFB1szZgJtXBhiBGi3CvDW2pJB8VAfjhL': {'ticker': 'TST',
   'name': 'Test',
   'launchpad_version': 'v0.7',
   'launch_account': 'B4f2YwEC2enqE2kkm3mYFosXjzGvYG864hKHFoqPH2XC',
   'sale_started': '2026-01-06',
   'sale_closed': '2026-01-06',
   'sale_completed': '2026-01-06',
   'usdc_committed': 6.0,
   'usdc_accepted': 6.0,
   'tokens_to_participants': 10000000,
   'ico_price_usd': 6e-07,
   'pair_id': None,
   'include': False,
   'source': 'on-chain Launch account (metadao.pull_launches)',
   'notes': None},
  '2Y7Wh61aZdgnfxaB4ueBmu8C3KXyhjVBfzyiBTcXeDeC': {'ticker': 'MTKN',
   'name': 'MyToken',
   'launchpad_version': 'v0.7',
   'launch_account': '9v82PoekYVAMEE9Fg3nFNYNVPybA3BYQCKxvKTXZAGkp',
   'sale_started': '2026-01-09',
   'sale_closed': '2026-01-09',
   'sale_completed': '2026-01-09',
   'usdc_committed': 2.0,
   'usdc_accepted': 2.0,
   'tokens_to_participants': 10000000,
   'ico_price_usd': 2e-07,
   'pair_id': None,
   'include': False,
   'source': 'on-chain Launch account (metadao.pull_launches)',
   'notes': None},
  '3k7Txeb1x6kJVgrdtEanFXz6ZfH37fPSR2bMq1gM9heR': {'ticker': 'MTKN',
   'name': 'MyToken',
   'launchpad_version': 'v0.7',
   'launch_account': 'D5UtuBuUy2j3ev5j2udQMLuuy6jQzLeuze3hTShW3XAa',
   'sale_started': '2026-01-09',
   'sale_closed': '2026-01-09',
   'sale_completed': '2026-01-09',
   'usdc_committed': 2.0,
   'usdc_accepted': 2.0,
   'tokens_to_participants': 10000000,
   'ico_price_usd': 2e-07,
   'pair_id': None,
   'include': False,
   'source': 'on-chain Launch account (metadao.pull_launches)',
   'notes': None},
  '8rda42wYxnkADAEwq6CNSPk72CjmFhwF1n1RxxiiUZ61': {'ticker': 'MTKN',
   'name': 'MyToken',
   'launchpad_version': 'v0.7',
   'launch_account': '9EU4EnB3NNQZ8y77wPp7PRcMcp1gC7koMZHHuV76qkeE',
   'sale_started': '2026-01-09',
   'sale_closed': '2026-01-09',
   'sale_completed': '2026-01-09',
   'usdc_committed': 2.0,
   'usdc_accepted': 2.0,
   'tokens_to_participants': 10000000,
   'ico_price_usd': 2e-07,
   'pair_id': None,
   'include': False,
   'source': 'on-chain Launch account (metadao.pull_launches)',
   'notes': None},
  '95FUf6qxFVCAm9XagFZpBi4F1A2EUkxhDRCewosfZfGy': {'ticker': 'HPBD',
   'name': 'HpBD',
   'launchpad_version': 'v0.7',
   'launch_account': '8mTJ737JaMBrV6dEBDsJifK4Zx9NYRkeEdNLPjqA2AAZ',
   'sale_started': '2026-01-09',

In [ ]:
# 2. AMM pair per included launch (pool id + exact trading start), filled into the config, then
# every swap on that pair for its first n_days (raw, swaps/{mint}.json). Both only touch launches
# that still lack a pair / a completed window; launches that closed before the swap feed starts
# (2025-10-09: Omnipair, mtnCapital) are reported and skipped.
metadao.pull_pairs(launch_config, metadao_output_dir)
metadao.pull_launch_swaps(launch_config, metadao_output_dir, n_days=n_days)

pairs: 14/16 included launches resolved; closed before the swap feed starts (2025-10-09), no price history: MTN, OMFG
swaps: 14 launches complete on file; no pair: MTN, OMFG

0

In [ ]:
# 3. Daily market data (tie-out only; kept once on file, force=True repulls), then the processed
# hourly VWAP file the chart reads (rebuilt only when an input changed; force=True rebuilds).
# The build line reports the ICO-price identity check and the swap-derived daily VWAP vs
# MetaDAO's daily endpoint on every full launch-day; any day off by more than 0.5% is listed.
metadao.pull_market_data(metadao_output_dir)
metadao.build_launch_prices(launch_config, metadao_output_dir, metadao_processed_dir, n_days=n_days);

[pull_market_data] failed: HTTP 400 HTTPError: 400 Client Error: Bad Request for url: https://market-api.metadao.fi/api/market-data?startDate=2025-10-01&endDate=2026-10-10
data/processed/metadao/launch-prices-7d.json: up to date (14 launches, built 0m ago), kept

In [ ]:
# HYPERLIQUID
# AQAv2 reserve yield: each UTC date the node charges the treasury deployer's native-USDC balance on
# HyperEVM (90% of the USDC backing HyperCore, the docs' 9:1 split) at the cost-adjusted AQA rate / 365.25,
# sums 30 days from activation (2026-08-27) and pays the Assistance Fund 8 days later. Official daily
# series from the /info endpoint (aqav2InterestHistory, no key); payments from the system interest
# address's ledger; the treasury balance is re-read at each 00:00 UTC block from an archive RPC as an
# independent tie-out (rpc.hyperliquid.xyz/evm is not an archive node); EFFR from FRED is the reference
# rate the forward estimate in example-analysis.ipynb is linked to.
token = 0             # AQAv2 token index (0 = USDC, the only aligned asset today)
max_stale_days = 0    # repull the series when its newest date is before today UTC

In [ ]:
# Refresh: the three pulls (each skipped when fresh; the treasury balances are append-only), then the
# period table with the tie-outs printed on one line: the interest identity on every day, the period
# boundaries, the treasury balance vs the charged base, and paid vs accrued once payments land.
periods = hyperliquid.refresh(hyperliquid_output_dir, token=token, max_stale_days=max_stale_days)
fred.pull_series(hyperliquid.DEFAULT_REFERENCE_SERIES, fred_api_key, fred_output_dir, observation_start='2026-01-01')
periods

aqav2 interest history (USDC): pulled 56 rows, 2026-08-16..2026-10-10 (45 active)
aqav2 payments (USDC): 6 ledger update(s), 2 payment(s) to the Assistance Fund; period 2 due 2026-11-02

treasury balances: 100%|██████████| 56/56 [03:36<00:00,  3.86s/pull]

treasury balances (USDC): read 56 new date(s) from https://rpc.hyperlend.finance/archive (56 on file, 2026-08-16..2026-10-10)
aqav2 (USDC): 45 active days in 2 period(s), 1 paid; identity holds to 9.9e-09 on every day; base = treasury balance at midnight on all 56 days read (52 exact to the cent); tie-out clean
FRED EFFR: pulled 195 observations, 2026-01-02..2026-10-08

,start,end,payment_date,days_sampled,status,interest_accrued,avg_supply,avg_rate,actual_paid,paid_date,difference,payment_tx
period,,,,,,,,,,,,
1,2026-08-27,2026-09-25,2026-10-03,30,paid,1.458078e+07,5.649550e+09,0.031419,1.458078e+07,2026-10-03,0.0,0x00000000000000000000000000000000000000000000...
2,2026-09-26,2026-10-25,2026-11-02,15,in-progress,8.041252e+06,6.058227e+09,0.032323,NaN,NaT,NaN,NaN

In [ ]:
# YAHOO FINANCE
start_date = "2020-01-01"
end_date   = datetime.datetime.today().strftime("%Y-%m-%d")

In [ ]:
# Test pull mcap to annualized metric multiple
tickers   = ['COIN', 'CRCL', 'HOOD', 'GEMI', 'LVS', 'DKNG', 'GOOGL', 'AAPL', 'MSFT', 'CME', 'ICE', 'NDAQ', 'FNF', 'SCHW', 'IBKR']
metrics = {'Total Revenue': 'total-revenue',
           'EBITDA': 'ebitda'}

yahoofinance.pull_mcap_to_annualized_metric_multiple(tickers, metrics, start_date, end_date, yahoofinance_output_dir)

Yahoo Finance multiples: 100%|██████████| 15/15 [00:12<00:00,  1.18pull/s]

All mcap-to-annualized-total-revenue data saved to data/raw/yahoofinance/mcap-to-annualized-total-revenue/
All mcap-to-annualized-ebitda data saved to data/raw/yahoofinance/mcap-to-annualized-ebitda/

In [ ]:
# VALUATION MULTIPLES
start_date = '2021-01-01'
end_date = datetime.datetime.today().strftime('%Y-%m-%d')

In [ ]:
# Pull top metrics from Messari using protocol index
# Categories are pulled from config/protocol_index.json

valuation_categories = ['perps_dexs', 'smart_contract_chains', 'borrow_lend_protocols', 'launchpads', 'liquid_staking', 'options', 'physical_tcg', 'dexs']

# Build categories dict with Messari slugs from the centralized index
categories = pi.get_categories_dict(categories=valuation_categories, source='messari')

metrics = ['marketcap',
           'price'
          ]

# Call the function
for category, assets in categories.items():
    print(f'{category}:') 
    print()
    messari.pull_asset_data(assets, metrics, start_date, end_date, messari_api_key, messari_output_dir)
    print()
    print('---------------------------')
print('Done')

perps_dexs:

Messari asset data: 100%|██████████| 16/16 [00:01<00:00,  9.17pull/s]

All marketcap data saved to data/raw/messari/marketcap/
All price data saved to data/raw/messari/price/

---------------------------
smart_contract_chains:

Messari asset data:  83%|████████▎ | 10/12 [00:00<00:00, 15.89pull/s]

  request failed: HTTP 404 HTTPError: https://api.messari.io/metrics/v2/assets/base/metrics/marketcap/time-series/1d?start=2021-01-01T00%3A00%3A00Z&end=2026-10-10T00%3A00%3A00Z
  request failed: HTTP 404 HTTPError: https://api.messari.io/metrics/v2/assets/base/metrics/price/time-series/1d?start=2021-01-01T00%3A00%3A00Z&end=2026-10-10T00%3A00%3A00Z

Messari asset data: 100%|██████████| 12/12 [00:01<00:00,  9.18pull/s]

All marketcap data saved to data/raw/messari/marketcap/
All price data saved to data/raw/messari/price/

Failed to pull (2):
  marketcap:
    - base
  price:
    - base

---------------------------
borrow_lend_protocols:

Messari asset data: 100%|██████████| 14/14 [00:00<00:00, 15.92pull/s]

All marketcap data saved to data/raw/messari/marketcap/
All price data saved to data/raw/messari/price/

---------------------------
launchpads:


All marketcap data saved to data/raw/messari/marketcap/
All price data saved to data/raw/messari/price/

---------------------------
liquid_staking:

Messari asset data: 100%|██████████| 12/12 [00:01<00:00,  7.84pull/s]

All marketcap data saved to data/raw/messari/marketcap/
All price data saved to data/raw/messari/price/

---------------------------
options:

Messari asset data: 100%|██████████| 2/2 [00:00<00:00, 10.84pull/s]

All marketcap data saved to data/raw/messari/marketcap/
All price data saved to data/raw/messari/price/

---------------------------
physical_tcg:

Messari asset data: 100%|██████████| 2/2 [00:00<00:00, 10.75pull/s]

All marketcap data saved to data/raw/messari/marketcap/
All price data saved to data/raw/messari/price/

---------------------------
dexs:

Messari asset data: 100%|██████████| 14/14 [00:00<00:00, 14.91pull/s]

All marketcap data saved to data/raw/messari/marketcap/
All price data saved to data/raw/messari/price/

---------------------------
Done

In [ ]:
# Pull bottom metrics from DefiLlama using protocol index
# Categories are pulled from config/protocol_index.json

# Metrics can accept 'dailyFees': 'fees', 'dailyRevenue': 'revenue', 'dailyHoldersRevenue': 'holders-revenue',
# 'dailyIncentives': 'incentives' (Pro only) and 'tvl': 'tvl'. Earnings is derived in the next cell.
metrics = {'dailyFees': 'fees',
          'dailyRevenue': 'revenue',
          'dailyHoldersRevenue': 'holders-revenue',
          'dailyIncentives': 'incentives',   # Pro only (DEFILLAMA_API_KEY); daily token incentives, USD
          'tvl': 'tvl'
}

# Build categories dict with DefiLlama slugs from the centralized index
categories = pi.get_categories_dict(categories=valuation_categories, source='defillama')

for category, assets in categories.items():
    print(f'{category}:') 
    print()
    defillama.pull_metric_data_by_asset(metrics, assets, defillama_output_dir)
    print()
    print('---------------------------')
print('Done')

perps_dexs:

DefiLlama metric data: 17 fresh file(s) skipped, 23 to pull

DefiLlama metric data:  43%|████▎     | 10/23 [00:02<00:01,  7.29pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/aster?dataType=dailyRevenue

DefiLlama metric data: 100%|██████████| 23/23 [00:03<00:00,  7.05pull/s]

All fees data saved to data/raw/defillama/fees/
All revenue data saved to data/raw/defillama/revenue/
All holders-revenue data saved to data/raw/defillama/holders-revenue/
All incentives data saved to data/raw/defillama/incentives/
All tvl data saved to data/raw/defillama/tvl/

Failed to pull (1):
  revenue:
    - aster

---------------------------
smart_contract_chains:

DefiLlama metric data: 4 fresh file(s) skipped, 26 to pull

DefiLlama metric data:  19%|█▉        | 5/26 [00:00<00:01, 11.86pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/protocol/bsc
  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/protocol/arbitrum

DefiLlama metric data:  73%|███████▎  | 19/26 [00:01<00:00, 17.84pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/protocol/base
  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/base?dataType=dailyHoldersRevenue

DefiLlama metric data: 100%|██████████| 26/26 [00:10<00:00,  2.45pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/arbitrum?dataType=dailyHoldersRevenue

All fees data saved to data/raw/defillama/fees/
All revenue data saved to data/raw/defillama/revenue/
All holders-revenue data saved to data/raw/defillama/holders-revenue/
All incentives data saved to data/raw/defillama/incentives/
All tvl data saved to data/raw/defillama/tvl/

Failed to pull (5):
  holders-revenue:
    - arbitrum
    - base
  tvl:
    - arbitrum
    - base
    - bnb

---------------------------
borrow_lend_protocols:

DefiLlama metric data: 29 fresh file(s) skipped, 6 to pull

DefiLlama metric data: 100%|██████████| 6/6 [00:01<00:00,  4.47pull/s]

All fees data saved to data/raw/defillama/fees/
All revenue data saved to data/raw/defillama/revenue/
All holders-revenue data saved to data/raw/defillama/holders-revenue/
All incentives data saved to data/raw/defillama/incentives/
All tvl data saved to data/raw/defillama/tvl/

---------------------------
launchpads:


All fees data saved to data/raw/defillama/fees/
All revenue data saved to data/raw/defillama/revenue/
All holders-revenue data saved to data/raw/defillama/holders-revenue/
All incentives data saved to data/raw/defillama/incentives/
All tvl data saved to data/raw/defillama/tvl/

---------------------------
liquid_staking:

DefiLlama metric data: 7 fresh file(s) skipped, 28 to pull

DefiLlama metric data:  21%|██▏       | 6/28 [00:00<00:01, 14.53pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/rocket-pool?dataType=dailyHoldersRevenue

DefiLlama metric data: 100%|██████████| 28/28 [00:05<00:00,  5.21pull/s]

All fees data saved to data/raw/defillama/fees/
All revenue data saved to data/raw/defillama/revenue/
All holders-revenue data saved to data/raw/defillama/holders-revenue/
All incentives data saved to data/raw/defillama/incentives/
All tvl data saved to data/raw/defillama/tvl/

Failed to pull (1):
  holders-revenue:
    - rocket-pool

---------------------------
options:

DefiLlama metric data: 5 fresh file(s) skipped, 0 to pull

All fees data saved to data/raw/defillama/fees/
All revenue data saved to data/raw/defillama/revenue/
All holders-revenue data saved to data/raw/defillama/holders-revenue/
All incentives data saved to data/raw/defillama/incentives/
All tvl data saved to data/raw/defillama/tvl/

---------------------------
physical_tcg:

DefiLlama metric data:  13%|█▎        | 8/60 [00:00<00:02, 19.51pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/courtyard?dataType=dailyHoldersRevenue
  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/beezie?dataType=dailyHoldersRevenue

DefiLlama metric data:  45%|████▌     | 27/60 [00:01<00:01, 29.02pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/monster?dataType=dailyHoldersRevenue
  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/pull.fun?dataType=dailyHoldersRevenue

DefiLlama metric data:  60%|██████    | 36/60 [00:01<00:00, 31.54pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/dyli?dataType=dailyHoldersRevenue
  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/shiny?dataType=dailyHoldersRevenue
  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/chapool?dataType=dailyHoldersRevenue

DefiLlama metric data:  80%|████████  | 48/60 [00:01<00:00, 27.41pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/yourgrails?dataType=dailyHoldersRevenue

DefiLlama metric data:  87%|████████▋ | 52/60 [00:01<00:00, 30.10pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/gemint?dataType=dailyHoldersRevenue

DefiLlama metric data:  95%|█████████▌| 57/60 [00:02<00:00, 25.73pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/pumpbox?dataType=dailyHoldersRevenue

DefiLlama metric data: 100%|██████████| 60/60 [00:02<00:00, 24.77pull/s]

All fees data saved to data/raw/defillama/fees/
All revenue data saved to data/raw/defillama/revenue/
All holders-revenue data saved to data/raw/defillama/holders-revenue/
All incentives data saved to data/raw/defillama/incentives/
All tvl data saved to data/raw/defillama/tvl/

Failed to pull (10):
  holders-revenue:
    - beezie
    - chapool
    - courtyard
    - dyli
    - gemint
    - monster
    - pull.fun
    - pumpbox
    - shiny
    - yourgrails

---------------------------
dexs:

DefiLlama metric data: 40 fresh file(s) skipped, 90 to pull

DefiLlama metric data:   2%|▏         | 2/90 [00:00<00:16,  5.38pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/dragon-swap?dataType=dailyRevenue
  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/ring-protocol?dataType=dailyHoldersRevenue
  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/project-x?dataType=dailyHoldersRevenue

DefiLlama metric data:  10%|█         | 9/90 [00:00<00:04, 19.72pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/dragon-swap?dataType=dailyFees

DefiLlama metric data:  17%|█▋        | 15/90 [00:00<00:03, 20.87pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/dragon-swap?dataType=dailyHoldersRevenue
  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/protocol/dragon-swap

DefiLlama metric data:  42%|████▏     | 38/90 [00:01<00:02, 21.66pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/protocol/ramses-exchange-hl

DefiLlama metric data:  88%|████████▊ | 79/90 [00:03<00:00, 23.21pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/fables?dataType=dailyHoldersRevenue

DefiLlama metric data: 100%|██████████| 90/90 [00:21<00:00,  4.16pull/s]

All fees data saved to data/raw/defillama/fees/
All revenue data saved to data/raw/defillama/revenue/
All holders-revenue data saved to data/raw/defillama/holders-revenue/
All incentives data saved to data/raw/defillama/incentives/
All tvl data saved to data/raw/defillama/tvl/

Failed to pull (8):
  fees:
    - dragon-swap
  holders-revenue:
    - dragon-swap
    - fables
    - project-x
    - ring-protocol
  revenue:
    - dragon-swap
  tvl:
    - dragon-swap
    - ramses-exchange-hl

---------------------------
Done

In [ ]:
# Derive daily earnings = revenue - incentives for every protocol pulled above (DefiLlama's Earnings
# definition). Written to data/raw/defillama/earnings/{Name}.json in the same shape as fees / revenue,
# so every chart and multiple that takes a metric dir can use 'earnings'. A protocol with no incentives
# tracked on DefiLlama gets earnings = revenue (listed below). Needs the incentives files (Pro key).
for category, assets in categories.items():
    print(f'{category}:')
    data_processing.build_earnings_series(assets, defillama_output_dir)

# Tie-out: monthly sums of each incentives file vs the Incentives line of DefiLlama's financial
# statement. Anything other than 'match' is a data gap worth knowing about before using earnings.
all_assets = {slug: name for assets in categories.values() for slug, name in assets.items()}
tieout = data_processing.check_incentives_tieout(all_assets, defillama_output_dir, months=12)
if not tieout.empty:
    display(tieout[tieout.status != 'match'])

perps_dexs:

DefiLlama metric data: 100%|██████████| 1/1 [00:00<00:00, 68.88pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/aster?dataType=dailyRevenue
  earnings: no revenue file for aster, skipped
  earnings = revenue (no incentives tracked on DefiLlama): hyperliquid, lighter, drift, dydx, jupiter, apex-protocol
smart_contract_chains:
  earnings = revenue (no incentives tracked on DefiLlama): solana, bnb, arbitrum, tron, base
borrow_lend_protocols:
  earnings = revenue (no incentives tracked on DefiLlama): kamino, maple-finance, spark
launchpads:
liquid_staking:
  earnings = revenue (no incentives tracked on DefiLlama): jito, rocket-pool, sanctum, marinade, kinetiq
options:
  earnings = revenue (no incentives tracked on DefiLlama): derive
physical_tcg:
  earnings = revenue (no incentives tracked on DefiLlama): collector-crypt, courtyard, beezie, phygitals, monster, pull.fun, dyli, shiny, yourgrails, chapool, gemint, pumpbox
dexs:

DefiLlama metric data: 100%|██████████| 1/1 [00:00<00:00, 21.37pull/s]

  request failed: HTTP 400 HTTPError: https://pro-api.llama.fi/***/api/summary/fees/dragon-swap?dataType=dailyRevenue
  earnings: no revenue file for dragon-swap, skipped

  earnings = revenue (no incentives tracked on DefiLlama): chainflip, project-x, ring-protocol, pulsex, metadao, ramses-exchange-hl, paycash, vvs-finance, aquarius-stellar, deepstate, humidifi, fables, hydrex
incentives tie-out: 229 month(s) match, 0 do not

Empty DataFrame
Columns: [protocol, emission_slug, month, chart_usd, statement_usd, diff, status]
Index: []

In [ ]:
# Universe earnings: every protocol DefiLlama tracks, rolled up to parents, from the universe
# snapshots already pulled above (fees, revenue and holders-revenue overviews, the /protocols list for
# mcap) plus one Pro request for the incentives snapshot. Stores fees / revenue / holders revenue /
# incentives as reported for each of DefiLlama's trailing windows (1, 7, 30 and 365 days; it reports
# no other totals universe-wide); the EARNINGS RANKINGS cells in example-analysis.ipynb pick the
# window with data_processing.load_universe_earnings(window_days=...). Rules: data_processing.UNIVERSE_EARNINGS_RULES.
defillama.pull_emissions_breakdown(defillama_output_dir)
universe = data_processing.build_universe_earnings(defillama_output_dir)  # returns the 30d view
universe.sort_values('ann_earnings', ascending=False).head(10)[
    ['name', 'category', 'mcap', 'ann_fees', 'ann_revenue', 'ann_holders_rev', 'ann_earnings',
     'earnings_minus_holders_rev', 'earnings_yield', 'incentives_status']]

In [ ]:
# Process valuation multiples for protocols & categories (FDV/MCAP / fees/revenue/holders-revenue)
# Uses standardized names from protocol index

# Build categories dict with standardized names from the centralized index
categories = pi.get_standard_names_dict(categories=valuation_categories)

data_processing.process_asset_metrics_data(
    categories=categories,
    output_filepath="data/processed/valuation-multiples/all-protocols-by-category.json"
)

Determining global date range...
Global date range: 2015-08-07 to 2026-10-10 (4083 days)

Processing category: perps_dexs
  Processing asset: hyperliquid
  Processing asset: lighter
  Processing asset: aster
    Warning: revenue file not found for aster, skipping this metric
    Replaced 2 outlier multiple values for aster (>100x from trailing 90d median) across 2 multiples
  Processing asset: drift
    Replaced 158 outlier multiple values for drift (>100x from trailing 90d median) across 6 multiples
  Processing asset: dydx
    Replaced 12 outlier multiple values for dydx (>100x from trailing 90d median) across 6 multiples
  Processing asset: jupiter
  Processing asset: gmx
    Replaced 2 outlier multiple values for gmx (>100x from trailing 90d median) across 2 multiples
  Processing asset: apex-protocol
    Replaced 88 outlier multiple values for apex-protocol (>100x from trailing 90d median) across 5 multiples

Processing category: smart_contract_chains
  Processing asset: ethereum
    Error loading TVL for ethereum: 'date'
  Processing asset: solana
    Error loading TVL for solana: 'date'
    Replaced 22 outlier multiple values for solana (>100x from trailing 90d median) across 6 multiples
  Processing asset: bnb
    Warning: TVL file not found for bnb, skipping TVL metric
  Processing asset: arbitrum
    Warning: holders-revenue file not found for arbitrum, skipping this metric
    Warning: TVL file not found for arbitrum, skipping TVL metric
    Replaced 25 outlier multiple values for arbitrum (>100x from trailing 90d median) across 6 multiples
  Processing asset: tron
    Error loading TVL for tron: 'date'
  Processing asset: base
    Warning: holders-revenue file not found for base, skipping this metric
    Warning: TVL file not found for base, skipping TVL metric
    Warning: Market cap file not found for base, skipping this asset

Processing category: borrow_lend_protocols
  Processing asset: aave
    Replaced 134 outlier multiple values for aave (>100x from trailing 90d median) across 17 multiples
  Processing asset: morpho
  Processing asset: compound-finance
  Processing asset: kamino
  Processing asset: maple-finance
    Replaced 117 outlier multiple values for maple-finance (>100x from trailing 90d median) across 6 multiples
  Processing asset: euler
    Replaced 336 outlier multiple values for euler (>100x from trailing 90d median) across 16 multiples
  Processing asset: spark
    Replaced 384 outlier multiple values for spark (>100x from trailing 90d median) across 8 multiples

Processing category: launchpads

Processing category: liquid_staking
  Processing asset: lido
  Processing asset: jito
  Processing asset: rocket-pool
    Warning: holders-revenue file not found for rocket-pool, skipping this metric
    Replaced 12 outlier multiple values for rocket-pool (>100x from trailing 90d median) across 2 multiples
  Processing asset: sanctum
    Replaced 396 outlier multiple values for sanctum (>100x from trailing 90d median) across 4 multiples
  Processing asset: ether-fi
  Processing asset: marinade
  Processing asset: kinetiq
    Warning: Market cap file not found for kinetiq, skipping this asset

Processing category: options
  Processing asset: derive

Processing category: physical_tcg
  Processing asset: collector-crypt
    Error loading TVL for collector-crypt: 'date'
    Replaced 4 outlier multiple values for collector-crypt (>100x from trailing 90d median) across 4 multiples
  Processing asset: courtyard
    Warning: holders-revenue file not found for courtyard, skipping this metric
    Error loading TVL for courtyard: 'date'
    Warning: Market cap file not found for courtyard, skipping this asset
  Processing asset: beezie
    Warning: holders-revenue file not found for beezie, skipping this metric
    Error loading TVL for beezie: 'date'
    Warning: Market cap file not found for beezie, skipping this asset
  Processing asset: phygitals
    Error loading TVL for phygitals: 'date'
    Warning: Market cap file not found for phygitals, skipping this asset
  Processing asset: monster
    Warning: holders-revenue file not found for monster, skipping this metric
    Error loading TVL for monster: 'date'
    Warning: Market cap file not found for monster, skipping this asset
  Processing asset: pull.fun
    Warning: holders-revenue file not found for pull.fun, skipping this metric
    Error loading TVL for pull.fun: 'date'
    Warning: Market cap file not found for pull.fun, skipping this asset
  Processing asset: dyli
    Warning: holders-revenue file not found for dyli, skipping this metric
    Error loading TVL for dyli: 'date'
    Warning: Market cap file not found for dyli, skipping this asset
  Processing asset: shiny
    Warning: holders-revenue file not found for shiny, skipping this metric
    Error loading TVL for shiny: 'date'
    Warning: Market cap file not found for shiny, skipping this asset
  Processing asset: yourgrails
    Warning: holders-revenue file not found for yourgrails, skipping this metric
    Error loading TVL for yourgrails: 'date'
    Warning: Market cap file not found for yourgrails, skipping this asset
  Processing asset: chapool
    Warning: holders-revenue file not found for chapool, skipping this metric
    Warning: Market cap file not found for chapool, skipping this asset
  Processing asset: gemint
    Warning: holders-revenue file not found for gemint, skipping this metric
    Error loading TVL for gemint: 'date'
    Warning: Market cap file not found for gemint, skipping this asset
  Processing asset: pumpbox
    Warning: holders-revenue file not found for pumpbox, skipping this metric
    Error loading TVL for pumpbox: 'date'
    Warning: Market cap file not found for pumpbox, skipping this asset

Processing category: dexs
  Processing asset: uniswap
  Processing asset: aerodrome
    Replaced 4 outlier multiple values for aerodrome (>100x from trailing 90d median) across 4 multiples
  Processing asset: orca
  Processing asset: chainflip
    Replaced 88 outlier multiple values for chainflip (>100x from trailing 90d median) across 10 multiples
  Processing asset: project-x
    Warning: holders-revenue file not found for project-x, skipping this metric
    Warning: Market cap file not found for project-x, skipping this asset
  Processing asset: thorchain-dex
    Warning: Market cap file not found for thorchain-dex, skipping this asset
  Processing asset: up
    Warning: Market cap file not found for up, skipping this asset
  Processing asset: pharaoh-exchange
    Warning: Market cap file not found for pharaoh-exchange, skipping this asset
  Processing asset: ring-protocol
    Warning: holders-revenue file not found for ring-protocol, skipping this metric
    Warning: Market cap file not found for ring-protocol, skipping this asset
  Processing asset: dragon-swap
    Warning: fees file not found for dragon-swap, skipping this metric
    Warning: revenue file not found for dragon-swap, skipping this metric
    Warning: holders-revenue file not found for dragon-swap, skipping this metric
    Warning: TVL file not found for dragon-swap, skipping TVL metric
    Warning: No bottom metrics found for dragon-swap, skipping this asset
  Processing asset: pulsex
    Warning: Market cap file not found for pulsex, skipping this asset
  Processing asset: velodrome
    Warning: Market cap file not found for velodrome, skipping this asset
  Processing asset: nest
    Warning: Market cap file not found for nest, skipping this asset
  Processing asset: metadao
    Warning: Market cap file not found for metadao, skipping this asset
  Processing asset: ramses-exchange-hl
    Warning: TVL file not found for ramses-exchange-hl, skipping TVL metric
    Warning: Market cap file not found for ramses-exchange-hl, skipping this asset
  Processing asset: paycash
    Warning: Market cap file not found for paycash, skipping this asset
  Processing asset: vvs-finance
  Processing asset: balancer
    Warning: Market cap file not found for balancer, skipping this asset
  Processing asset: aquarius-stellar
    Warning: Market cap file not found for aquarius-stellar, skipping this asset
  Processing asset: tokenlon
    Replaced 2 outlier multiple values for tokenlon (>100x from trailing 90d median) across 1 multiples
  Processing asset: deepstate
    Warning: Market cap file not found for deepstate, skipping this asset
  Processing asset: hyperswap
    Warning: Market cap file not found for hyperswap, skipping this asset
  Processing asset: humidifi
    Error loading TVL for humidifi: 'date'
    Replaced 900 outlier multiple values for humidifi (>100x from trailing 90d median) across 16 multiples
  Processing asset: fables
    Warning: holders-revenue file not found for fables, skipping this metric
    Warning: Market cap file not found for fables, skipping this asset
  Processing asset: hydrex
    Warning: Market cap file not found for hydrex, skipping this asset
  Processing asset: quickswap
    Warning: Market cap file not found for quickswap, skipping this asset

Data saved to data/processed/valuation-multiples/all-protocols-by-category.json

In [ ]:
# Test functions to pull aggregated valuation multiples by category

# Calculate weighted multiples
breakout_assets = {
    'perps_dexs': None,
    'smart_contract_chains': None,
    'borrow_lend_protocols': None,
    'launchpads': None,
    'liquid_staking': None,
    'depin': None,
    'yield': None,
    'nft_marketplace': None,
    'physical_tcg': None,
    'misc': None
}

data_processing.calculate_weighted_multiples(
    input_filepath="data/processed/valuation-multiples/all-protocols-by-category.json",
    categories=categories,
    breakout_assets=breakout_assets,
    start_date='2021-01-01',
    output_filepath="data/processed/valuation-multiples/weighted-multiples-by-category.json"
)

Weighted multiples data saved to data/processed/valuation-multiples/weighted-multiples-by-category.json

In [ ]:
# OTHER PROCESSED DATA

In [ ]:
# Test function to process and save annualized volatility data as JSON
trailing_window=7 # defaults to 7

data_processing.process_annualized_volatility_data(start_date, trailing_window)

Saved aave data to data/processed/annualized-volatility/aave.json
Saved aerodrome data to data/processed/annualized-volatility/aerodrome.json
Saved apex-protocol data to data/processed/annualized-volatility/apex-protocol.json
Saved arbitrum data to data/processed/annualized-volatility/arbitrum.json
Saved aster data to data/processed/annualized-volatility/aster.json
Saved bitcoin data to data/processed/annualized-volatility/bitcoin.json
Saved bnb data to data/processed/annualized-volatility/bnb.json
Saved chainflip data to data/processed/annualized-volatility/chainflip.json
Saved collector-crypt data to data/processed/annualized-volatility/collector-crypt.json
Saved compound-finance data to data/processed/annualized-volatility/compound-finance.json
Saved derive data to data/processed/annualized-volatility/derive.json
Saved drift data to data/processed/annualized-volatility/drift.json
Saved dydx data to data/processed/annualized-volatility/dydx.json
Saved ether-fi data to data/processed/annualized-volatility/ether-fi.json
Saved ethereum data to data/processed/annualized-volatility/ethereum.json
Saved euler data to data/processed/annualized-volatility/euler.json
Saved gmx data to data/processed/annualized-volatility/gmx.json
Saved humidifi data to data/processed/annualized-volatility/humidifi.json
Saved hyperliquid data to data/processed/annualized-volatility/hyperliquid.json
Saved jito data to data/processed/annualized-volatility/jito.json
Saved jupiter data to data/processed/annualized-volatility/jupiter.json
Saved kamino data to data/processed/annualized-volatility/kamino.json
Saved lido data to data/processed/annualized-volatility/lido.json
Saved lighter data to data/processed/annualized-volatility/lighter.json
Saved maple-finance data to data/processed/annualized-volatility/maple-finance.json
Saved marinade data to data/processed/annualized-volatility/marinade.json
Saved morpho data to data/processed/annualized-volatility/morpho.json
Saved orca data to data/processed/annualized-volatility/orca.json
Saved rocket-pool data to data/processed/annualized-volatility/rocket-pool.json
Saved sanctum data to data/processed/annualized-volatility/sanctum.json
Saved solana data to data/processed/annualized-volatility/solana.json
Saved spark data to data/processed/annualized-volatility/spark.json
Saved tokenlon data to data/processed/annualized-volatility/tokenlon.json
Saved tron data to data/processed/annualized-volatility/tron.json
Saved uniswap data to data/processed/annualized-volatility/uniswap.json
Saved vvs-finance data to data/processed/annualized-volatility/vvs-finance.json
Done